package khanzahmsanjungan;

import fungsi.koneksiDB;
import fungsi.validasi;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

public final class DlgCariPoliBPJS extends widget.Dialog {

    private final DefaultTableModel tabMode;
    private final validasi Valid = new validasi();
    private final Connection koneksi = koneksiDB.condb();

    public DlgCariPoliBPJS(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        Object[] row = {"Kode Unit", "Nama Unit"};
        tabMode = new DefaultTableModel(null, row) {
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        tbPoli.setModel(tabMode);

        for (int i = 0; i < 2; i++) {
            TableColumn column = tbPoli.getColumnModel().getColumn(i);
            if (i == 1) {
                column.setPreferredWidth(500);
            } else {
                column.setMinWidth(0);
                column.setMaxWidth(0);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Scroll = new widget.ScrollPane();
        tbPoli = new widget.Table();
        panelBawah = new widget.Panel();
        btnKeluar = new widget.Button();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        Scroll.setName("Scroll"); // NOI18N

        tbPoli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbPoliMouseReleased(evt);
            }
        });
        Scroll.setViewportView(tbPoli);

        getContentPane().add(Scroll, java.awt.BorderLayout.CENTER);

        panelBawah.setName("panelBawah"); // NOI18N
        panelBawah.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        btnKeluar.setBackground(new java.awt.Color(255, 255, 255));
        btnKeluar.setForeground(new java.awt.Color(255, 23, 26));
        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/exit.png"))); // NOI18N
        btnKeluar.setText("KELUAR");
        btnKeluar.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        btnKeluar.setName("btnKeluar"); // NOI18N
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        panelBawah.add(btnKeluar);

        getContentPane().add(panelBawah, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Valid.tabelKosong(tabMode);
        try (ResultSet rs = koneksi.createStatement().executeQuery("select * from maping_poli_bpjs")) {
            while (rs.next()) {
                tabMode.addRow(new String[] {rs.getString("kd_poli_bpjs"), rs.getString("nm_poli_bpjs")});
            }
        } catch (Exception e) {
            System.out.println("Notif : " + e);
        }
    }//GEN-LAST:event_formWindowActivated

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void tbPoliMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPoliMouseReleased
        dispose();
    }//GEN-LAST:event_tbPoliMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.ScrollPane Scroll;
    private widget.Button btnKeluar;
    private widget.Panel panelBawah;
    private widget.Table tbPoli;
    // End of variables declaration//GEN-END:variables

    public boolean hasSelection() {
        return tbPoli.getSelectedRow() >= 0;
    }

    public Object getSelectedRow(int column) {
        return tbPoli.getValueAt(tbPoli.getSelectedRow(), column);
    }
}
