package khanzahmsanjungan;

import fungsi.koneksiDB;
import fungsi.validasi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

public final class DlgCariPoli extends widget.Dialog {

    private final DefaultTableModel tabMode;
    private final validasi Valid = new validasi();
    private final Connection koneksi = koneksiDB.condb();

    public DlgCariPoli(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        Object[] row = {"Kode Unit", "Nama Unit", "registrasi", "registrasilama"};
        tabMode = new DefaultTableModel(null, row) {
            Class[] type = new Class[] {
                java.lang.String.class, java.lang.String.class,
                java.lang.Double.class, java.lang.Double.class
            };

            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return type[columnIndex];
            }
        };
        tbPoli.setModel(tabMode);

        for (int i = 0; i < 4; i++) {
            TableColumn column = tbPoli.getColumnModel().getColumn(i);
            if (i == 0) {
                column.setPreferredWidth(100);
            } else if (i == 1) {
                column.setPreferredWidth(500);
            } else {
                column.setMinWidth(0);
                column.setMaxWidth(0);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Scroll = new widget.ScrollPane();
        tbPoli = new widget.Table();
        panelBawah = new widget.Panel();
        btnKeluar = new widget.Button();

        tbPoli.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbPoli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbPoliMouseReleased(evt);
            }
        });
        Scroll.setViewportView(tbPoli);

        getContentPane().add(Scroll, java.awt.BorderLayout.CENTER);

        panelBawah.setName("panelBawah"); // NOI18N
        panelBawah.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        btnKeluar.setBackground(new java.awt.Color(255, 255, 255));
        btnKeluar.setForeground(new java.awt.Color(255, 23, 26));
        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/exit.png"))); // NOI18N
        btnKeluar.setText("KELUAR");
        btnKeluar.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        btnKeluar.setName("btnKeluar"); // NOI18N
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        panelBawah.add(btnKeluar);

        getContentPane().add(panelBawah, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void tbPoliMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPoliMouseReleased
        dispose();
    }//GEN-LAST:event_tbPoliMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.ScrollPane Scroll;
    private widget.Button btnKeluar;
    private widget.Panel panelBawah;
    private widget.Table tbPoli;
    // End of variables declaration//GEN-END:variables

    public void tampil(String hari) {
        Valid.tabelKosong(tabMode);
        try (PreparedStatement ps = koneksi.prepareStatement(
            "select p.kd_poli, p.nm_poli, p.registrasi, p.registrasilama from poliklinik as p where p.status = '1' and " +
            "exists(select * from jadwal as j where j.kd_poli = p.kd_poli and j.hari_kerja = ?) order by p.nm_poli"
        )) {
            ps.setString(1, hari);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    tabMode.addRow(new Object[] {
                        rs.getString("kd_poli"), rs.getString("nm_poli"),
                        rs.getDouble("registrasi"), rs.getDouble("registrasilama")
                    });
                }
            }
        } catch (Exception e) {
            System.out.println("Notif : " + e);
        }
    }

    public void tampilPoliMapping(String kodePoliBPJS) {
        Valid.tabelKosong(tabMode);
        try (PreparedStatement ps = koneksi.prepareStatement(
            "select m.kd_poli, m.nm_poli, m.registrasi, m.registrasilama from poliklinik as p where " +
            "exists(select * from maping_poli_bpjs as m where m.kd_poli_rs = p.kd_poli and m.kd_poli_bpjs = ?)"
        )) {
            ps.setString(1, kodePoliBPJS);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    tabMode.addRow(new Object[] {
                        rs.getString("kd_poli"), rs.getString("nm_poli"),
                        rs.getDouble("registrasi"), rs.getDouble("registrasilama")
                    });
                }
            }
        } catch (Exception e) {
            System.out.println("Notif : " + e);
        }
    }

    public boolean hasSelection() {
        return tbPoli.getSelectedRow() >= 0;
    }

    public Object getSelectedRow(int column) {
        return tbPoli.getValueAt(tbPoli.getSelectedRow(), column);
    }
}
