/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * DlgAdmin.java
 *
 * Created on 21 Jun 10, 20:53:44
 */
package setting;

import fungsi.batasInput;
import fungsi.WarnaTable;
import fungsi.validasi;
import fungsi.sekuel;
import fungsi.koneksiDB;
import java.awt.Canvas;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.RejectedExecutionException;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import org.apache.commons.codec.binary.Base64;
import simrskhanza.frmUtama;

/**
 *
 * @author perpustakaan
 */
public class DlgSetAplikasi extends javax.swing.JDialog {
    private final DefaultTableModel tabMode;
    private Connection koneksi = koneksiDB.condb();
    private sekuel Sequel = new sekuel();
    private validasi Valid = new validasi();
    private final ExecutorService executor = Executors.newSingleThreadExecutor();
    private volatile boolean ceksukses = false;
    private PreparedStatement ps;
    private ResultSet rs;

    /**
     * Creates new form DlgAdmin
     *
     * @param parent
     * @param modal
     */
    public DlgSetAplikasi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocation(10, 10);
        setSize(457, 249);

        tabMode = new DefaultTableModel(null, new Object[] {
            "Faskes", "Alamat", "Kota", "Propinsi", "Aktifkan?", "Wallpaper", "Kontak", "Email", "Logo", "Kode PPK BPJS",
            "Kode PPK Apotek Online", "Kode PPK Inhealth", "Kode PPK Kemenkes", "Batas Edit 2x24 Jam", "Sistem Import Koding"
        }) {
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };

        tbAdmin.setModel(tabMode);
        //runBackground(() ->tampil());
        //tbJabatan.setDefaultRenderer(Object.class, new WarnaTable(Scroll.getBackground(),Color.GREEN));
        tbAdmin.setPreferredScrollableViewportSize(new Dimension(500,500));
        tbAdmin.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        for (int i = 0; i < tabMode.getColumnCount(); i++) {
            TableColumn column = tbAdmin.getColumnModel().getColumn(i);
            if (i == 0) {
                column.setPreferredWidth(250);
            } else {
                column.setPreferredWidth(150);
            }
        }

        tbAdmin.setDefaultRenderer(Object.class, new WarnaTable());

        Nm.setDocument(new batasInput((byte) 60).getKata(Nm));
        Almt.setDocument(new batasInput((int) 150).getKata(Almt));
        Kota.setDocument(new batasInput((byte) 30).getKata(Kota));
        Propinsi.setDocument(new batasInput((byte) 30).getKata(Propinsi));
        Kontak.setDocument(new batasInput((byte) 50).getKata(Kontak));
        Email.setDocument(new batasInput((byte) 50).getKata(Email));
        kdPPKBPJS.setDocument(new batasInput((byte) 15).getKata(kdPPKBPJS));
        kdPPKInhealth.setDocument(new batasInput((byte) 15).getKata(kdPPKInhealth));
        kdPPKKemenkes.setDocument(new batasInput((byte) 15).getKata(kdPPKKemenkes));
        kdPPKApotekOnline.setDocument(new batasInput((byte) 15).getKata(kdPPKKemenkes));
    }
    private javax.swing.JFileChooser jfc = new JFileChooser();
    private javax.swing.JFileChooser jfc2 = new JFileChooser();
    private FileFilter jpgFilter = new FileNameExtensionFilter("Gambar JPEG", "jpg");
    private FileFilter gifFilter = new FileNameExtensionFilter("Gambar GIF", "gif");
    private FileFilter pngFilter = new FileNameExtensionFilter("Gambar PNG", "png");
    private FileFilter bothFilter = new FileNameExtensionFilter("Gambar JPEG dan GIF dan PNG", "jpg", "gif", "png");

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        Scroll = new widget.ScrollPane();
        tbAdmin = new widget.Table();
        panelisi1 = new widget.panelisi();
        BtnSimpan = new widget.Button();
        BtnBatal = new widget.Button();
        BtnHapus = new widget.Button();
        BtnKeluar = new widget.Button();
        panelGlass1 = new widget.panelGlass();
        label35 = new widget.Label();
        Nm = new widget.TextBox();
        label34 = new widget.Label();
        Almt = new widget.TextBox();
        label36 = new widget.Label();
        Kota = new widget.TextBox();
        label37 = new widget.Label();
        Propinsi = new widget.TextBox();
        scrollPane2 = new widget.ScrollPane();
        PhotoGambar = new Painter();
        BtnCariGb = new widget.Button();
        EGb = new widget.TextBox();
        label38 = new widget.Label();
        YesNo = new widget.ComboBox();
        label39 = new widget.Label();
        Kontak = new widget.TextBox();
        label40 = new widget.Label();
        Email = new widget.TextBox();
        scrollPane3 = new widget.ScrollPane();
        PhotoLogo = new Painter();
        label41 = new widget.Label();
        ELogo = new widget.TextBox();
        BtnCariLogo = new widget.Button();
        label42 = new widget.Label();
        kdPPKBPJS = new widget.TextBox();
        label43 = new widget.Label();
        kdPPKInhealth = new widget.TextBox();
        label44 = new widget.Label();
        kdPPKKemenkes = new widget.TextBox();
        label13 = new widget.Label();
        SistemImportKoding = new widget.ComboBox();
        label14 = new widget.Label();
        BatasEdit2x24jam = new widget.ComboBox();
        label45 = new widget.Label();
        label46 = new widget.Label();
        kdPPKApotekOnline = new widget.TextBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Setup Aplikasi ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        Scroll.setName("Scroll"); // NOI18N
        Scroll.setOpaque(true);

        tbAdmin.setToolTipText("Silahkan klik untuk memilih data yang mau diedit ataupun dihapus");
        tbAdmin.setName("tbAdmin"); // NOI18N
        tbAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAdminMouseClicked(evt);
            }
        });
        tbAdmin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbAdminKeyPressed(evt);
            }
        });
        Scroll.setViewportView(tbAdmin);

        internalFrame1.add(Scroll, java.awt.BorderLayout.CENTER);

        panelisi1.setName("panelisi1"); // NOI18N
        panelisi1.setPreferredSize(new java.awt.Dimension(100, 54));
        panelisi1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        BtnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/save-16x16.png"))); // NOI18N
        BtnSimpan.setMnemonic('S');
        BtnSimpan.setText("Simpan");
        BtnSimpan.setToolTipText("Alt+S");
        BtnSimpan.setName("BtnSimpan"); // NOI18N
        BtnSimpan.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });
        panelisi1.add(BtnSimpan);

        BtnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Cancel-2-16x16.png"))); // NOI18N
        BtnBatal.setMnemonic('B');
        BtnBatal.setText("Baru");
        BtnBatal.setToolTipText("Alt+B");
        BtnBatal.setName("BtnBatal"); // NOI18N
        BtnBatal.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatalActionPerformed(evt);
            }
        });
        panelisi1.add(BtnBatal);

        BtnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/stop_f2.png"))); // NOI18N
        BtnHapus.setMnemonic('H');
        BtnHapus.setText("Hapus");
        BtnHapus.setToolTipText("Alt+H");
        BtnHapus.setName("BtnHapus"); // NOI18N
        BtnHapus.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });
        panelisi1.add(BtnHapus);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        panelisi1.add(BtnKeluar);

        internalFrame1.add(panelisi1, java.awt.BorderLayout.PAGE_END);

        panelGlass1.setName("panelGlass1"); // NOI18N
        panelGlass1.setPreferredSize(new java.awt.Dimension(200, 312));
        panelGlass1.setLayout(null);

        label35.setText("Faskes :");
        label35.setName("label35"); // NOI18N
        label35.setPreferredSize(new java.awt.Dimension(35, 23));
        panelGlass1.add(label35);
        label35.setBounds(0, 10, 70, 23);

        Nm.setName("Nm"); // NOI18N
        panelGlass1.add(Nm);
        Nm.setBounds(75, 10, 220, 23);

        label34.setText("Alamat :");
        label34.setName("label34"); // NOI18N
        label34.setPreferredSize(new java.awt.Dimension(35, 23));
        panelGlass1.add(label34);
        label34.setBounds(0, 40, 70, 23);

        Almt.setName("Almt"); // NOI18N
        panelGlass1.add(Almt);
        Almt.setBounds(75, 40, 220, 23);

        label36.setText("Kota :");
        label36.setName("label36"); // NOI18N
        label36.setPreferredSize(new java.awt.Dimension(35, 23));
        panelGlass1.add(label36);
        label36.setBounds(0, 70, 70, 23);

        Kota.setName("Kota"); // NOI18N
        panelGlass1.add(Kota);
        Kota.setBounds(75, 70, 220, 23);

        label37.setText("Aktifkan WP ?");
        label37.setName("label37"); // NOI18N
        label37.setPreferredSize(new java.awt.Dimension(35, 23));
        panelGlass1.add(label37);
        label37.setBounds(304, 10, 69, 23);

        Propinsi.setName("Propinsi"); // NOI18N
        panelGlass1.add(Propinsi);
        Propinsi.setBounds(75, 100, 220, 23);

        scrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        scrollPane2.setName("scrollPane2"); // NOI18N

        PhotoGambar.setBackground(new java.awt.Color(245, 255, 235));
        PhotoGambar.setForeground(new java.awt.Color(235, 255, 235));
        PhotoGambar.setName("PhotoGambar"); // NOI18N
        scrollPane2.setViewportView(PhotoGambar);

        panelGlass1.add(scrollPane2);
        scrollPane2.setBounds(304, 40, 302, 203);

        BtnCariGb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/190.png"))); // NOI18N
        BtnCariGb.setMnemonic('C');
        BtnCariGb.setToolTipText("Alt+C");
        BtnCariGb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BtnCariGb.setName("BtnCariGb"); // NOI18N
        BtnCariGb.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnCariGb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariGbActionPerformed(evt);
            }
        });
        panelGlass1.add(BtnCariGb);
        BtnCariGb.setBounds(578, 10, 28, 23);

        EGb.setEditable(false);
        EGb.setName("EGb"); // NOI18N
        EGb.setPreferredSize(new java.awt.Dimension(207, 23));
        panelGlass1.add(EGb);
        EGb.setBounds(431, 10, 143, 23);

        label38.setText("Propinsi :");
        label38.setName("label38"); // NOI18N
        label38.setPreferredSize(new java.awt.Dimension(35, 23));
        panelGlass1.add(label38);
        label38.setBounds(0, 100, 70, 23);

        YesNo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yes", "No" }));
        YesNo.setName("YesNo"); // NOI18N
        YesNo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                YesNoItemStateChanged(evt);
            }
        });
        panelGlass1.add(YesNo);
        YesNo.setBounds(377, 10, 50, 23);

        label39.setText("Kontak :");
        label39.setName("label39"); // NOI18N
        label39.setPreferredSize(new java.awt.Dimension(35, 23));
        panelGlass1.add(label39);
        label39.setBounds(0, 130, 70, 23);

        Kontak.setName("Kontak"); // NOI18N
        panelGlass1.add(Kontak);
        Kontak.setBounds(75, 130, 220, 23);

        label40.setText("Email :");
        label40.setName("label40"); // NOI18N
        label40.setPreferredSize(new java.awt.Dimension(35, 23));
        panelGlass1.add(label40);
        label40.setBounds(0, 160, 70, 23);

        Email.setName("Email"); // NOI18N
        panelGlass1.add(Email);
        Email.setBounds(75, 160, 220, 23);

        scrollPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        scrollPane3.setName("scrollPane3"); // NOI18N

        PhotoLogo.setBackground(new java.awt.Color(245, 255, 235));
        PhotoLogo.setForeground(new java.awt.Color(235, 255, 235));
        PhotoLogo.setName("PhotoLogo"); // NOI18N
        scrollPane3.setViewportView(PhotoLogo);

        panelGlass1.add(scrollPane3);
        scrollPane3.setBounds(610, 40, 203, 203);

        label41.setText("Logo :");
        label41.setName("label41"); // NOI18N
        label41.setPreferredSize(new java.awt.Dimension(35, 23));
        panelGlass1.add(label41);
        label41.setBounds(610, 10, 31, 23);

        ELogo.setEditable(false);
        ELogo.setName("ELogo"); // NOI18N
        ELogo.setPreferredSize(new java.awt.Dimension(207, 23));
        panelGlass1.add(ELogo);
        ELogo.setBounds(645, 10, 136, 23);

        BtnCariLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/190.png"))); // NOI18N
        BtnCariLogo.setMnemonic('C');
        BtnCariLogo.setToolTipText("Alt+C");
        BtnCariLogo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BtnCariLogo.setName("BtnCariLogo"); // NOI18N
        BtnCariLogo.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnCariLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariLogoActionPerformed(evt);
            }
        });
        panelGlass1.add(BtnCariLogo);
        BtnCariLogo.setBounds(785, 10, 28, 23);

        label42.setText("BPJS :");
        label42.setName("label42"); // NOI18N
        label42.setPreferredSize(new java.awt.Dimension(35, 23));
        panelGlass1.add(label42);
        label42.setBounds(30, 280, 60, 23);

        kdPPKBPJS.setName("kdPPKBPJS"); // NOI18N
        panelGlass1.add(kdPPKBPJS);
        kdPPKBPJS.setBounds(94, 280, 110, 23);

        label43.setText("Inhealth :");
        label43.setName("label43"); // NOI18N
        label43.setPreferredSize(new java.awt.Dimension(35, 23));
        panelGlass1.add(label43);
        label43.setBounds(208, 280, 50, 23);

        kdPPKInhealth.setName("kdPPKInhealth"); // NOI18N
        panelGlass1.add(kdPPKInhealth);
        kdPPKInhealth.setBounds(262, 280, 110, 23);

        label44.setText(" Kemenkes :");
        label44.setName("label44"); // NOI18N
        label44.setPreferredSize(new java.awt.Dimension(35, 23));
        panelGlass1.add(label44);
        label44.setBounds(376, 280, 60, 23);

        kdPPKKemenkes.setName("kdPPKKemenkes"); // NOI18N
        panelGlass1.add(kdPPKKemenkes);
        kdPPKKemenkes.setBounds(440, 280, 110, 23);

        label13.setText("Import koding hasil bridging klaim :");
        label13.setName("label13"); // NOI18N
        label13.setPreferredSize(new java.awt.Dimension(70, 23));
        panelGlass1.add(label13);
        label13.setBounds(58, 220, 164, 23);

        SistemImportKoding.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "INA-CBG", "IDRG", "" }));
        SistemImportKoding.setSelectedIndex(2);
        SistemImportKoding.setName("SistemImportKoding"); // NOI18N
        panelGlass1.add(SistemImportKoding);
        SistemImportKoding.setBounds(225, 220, 70, 23);

        label14.setText("Aktifkan batas edit 2x24 jam :");
        label14.setName("label14"); // NOI18N
        label14.setPreferredSize(new java.awt.Dimension(70, 23));
        panelGlass1.add(label14);
        label14.setBounds(86, 190, 145, 23);

        BatasEdit2x24jam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yes", "No" }));
        BatasEdit2x24jam.setName("BatasEdit2x24jam"); // NOI18N
        panelGlass1.add(BatasEdit2x24jam);
        BatasEdit2x24jam.setBounds(235, 190, 60, 23);

        label45.setText("Integrasi (Kode Faskes/PPK) :");
        label45.setName("label45"); // NOI18N
        label45.setPreferredSize(new java.awt.Dimension(35, 23));
        panelGlass1.add(label45);
        label45.setBounds(0, 250, 160, 23);

        label46.setText(" Apotek BPJS :");
        label46.setName("label46"); // NOI18N
        label46.setPreferredSize(new java.awt.Dimension(35, 23));
        panelGlass1.add(label46);
        label46.setBounds(554, 280, 70, 23);

        kdPPKApotekOnline.setName("kdPPKApotekOnline"); // NOI18N
        panelGlass1.add(kdPPKApotekOnline);
        kdPPKApotekOnline.setBounds(628, 280, 110, 23);

        internalFrame1.add(panelGlass1, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAdminMouseClicked
        if (tabMode.getRowCount() != 0) {
            try {
                getData();
            } catch (java.lang.NullPointerException e) {

            }
        }
    }//GEN-LAST:event_tbAdminMouseClicked

    private void tbAdminKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbAdminKeyPressed
        if (tabMode.getRowCount() != 0) {
            if ((evt.getKeyCode() == KeyEvent.VK_ENTER) || (evt.getKeyCode() == KeyEvent.VK_UP) || (evt.getKeyCode() == KeyEvent.VK_DOWN)) {
                try {
                    getData();
                } catch (java.lang.NullPointerException e) {
                }
            }
        }
    }//GEN-LAST:event_tbAdminKeyPressed

    private void BtnCariGbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariGbActionPerformed
        jfc.setAcceptAllFileFilterUsed(false);
        jfc.addChoosableFileFilter(jpgFilter);
        jfc.addChoosableFileFilter(gifFilter);
        jfc.addChoosableFileFilter(pngFilter);
        jfc.addChoosableFileFilter(bothFilter);
        if (jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            String f = jfc.getSelectedFile().toString();
            EGb.setText(f);
            //lGambar.setIcon(new ImageIcon(f));
            ((Painter) PhotoGambar).setImage(f);

        }
    }//GEN-LAST:event_BtnCariGbActionPerformed

    private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanActionPerformed
        if (Nm.getText().trim().equals("")) {
            Valid.textKosong(Nm, "Nama Faskes");
        } else if (Almt.getText().isBlank()) {
            Valid.textKosong(Almt, "Alamat");
        } else if (Kota.getText().isBlank()) {
            Valid.textKosong(Kota, "Kota/Kabupaten");
        } else if (Propinsi.getText().isBlank()) {
            Valid.textKosong(Propinsi, "Propinsi");
        } else if (Kontak.getText().isBlank()) {
            Valid.textKosong(Kontak, "Kontak");
        } else if (Email.getText().isBlank()) {
            Valid.textKosong(Email, "Email");
        } else {
            if (EGb.getText().isBlank()) {
                YesNo.setSelectedItem("No");
                EGb.setText("./setting/wallpaper.jpg");
            }

            if (ELogo.getText().isBlank()) {
                ELogo.setText("./setting/logo.jpg");
            }

            String gb = "", logo = "";
            File fgb = new File(EGb.getText()),
                flogo = new File(ELogo.getText());

            try (FileInputStream fs1 = new FileInputStream(fgb); FileInputStream fs2 = new FileInputStream(flogo)) {
                byte[] b1 = new byte[(int) fgb.length()],
                    b2 = new byte[(int) flogo.length()];
                fs1.read(b1);
                fs2.read(b2);
                gb = Base64.encodeBase64String(b1);
                logo = Base64.encodeBase64String(b2);
            } catch (Exception e) {
                System.out.println("Notif : " + e);
            }

            Sequel.menghapusSmc("setting");
            if (Sequel.executeRawSmc("insert into setting (nama_instansi, alamat_instansi, kabupaten, propinsi, kontak, email, aktifkan, kode_ppk, kode_ppkinhealth, kode_ppkkemenkes, " +
                "pemberlakuan_2x24_jam, sistem_import_koding, kode_ppkapotek, wallpaper, logo) values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, from_base64(?), from_base64(?))",
                Nm.getText(), Almt.getText(), Kota.getText(), Propinsi.getText(), Kontak.getText(), Email.getText(), YesNo.getSelectedItem().toString(), kdPPKBPJS.getText(),
                kdPPKInhealth.getText(), kdPPKKemenkes.getText(), BatasEdit2x24jam.getSelectedItem().toString(), SistemImportKoding.getSelectedItem().toString(),
                kdPPKApotekOnline.getText(), gb, logo)
            ) {
                emptTeks();
                runBackground(() ->tampil());
                JOptionPane.showMessageDialog(null, "Pengaturan berhasil disimpan..!!");
            } else {
                JOptionPane.showMessageDialog(null, "Pengaturan gagal disimpan..!!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            }

            frmUtama.getInstance().isWall();
        }
    }//GEN-LAST:event_BtnSimpanActionPerformed

    private void BtnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatalActionPerformed
        emptTeks();
    }//GEN-LAST:event_BtnBatalActionPerformed

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
        if (tabMode.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Maaf, data sudah habis...!!!!");
            Nm.requestFocus();
        }else if(Nm.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Gagal menghapus. Pilih dulu data yang mau dihapus.\nKlik data pada table untuk memilih...!!!!");
        }else if(! Nm.getText().trim().equals("")){
            Sequel.queryu("delete from setting ");
            runBackground(() ->tampil());
            emptTeks();
            tampil();
        }
    }//GEN-LAST:event_BtnHapusActionPerformed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        runBackground(() ->tampil());
    }//GEN-LAST:event_formWindowOpened

    private void BtnCariLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariLogoActionPerformed
        jfc2.setAcceptAllFileFilterUsed(false);
        jfc2.addChoosableFileFilter(jpgFilter);
        jfc2.addChoosableFileFilter(gifFilter);
        jfc2.addChoosableFileFilter(pngFilter);
        jfc2.addChoosableFileFilter(bothFilter);
        if (jfc2.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            String f = jfc2.getSelectedFile().toString();
            ELogo.setText(f);
            //lGambar.setIcon(new ImageIcon(f));
            ((Painter) PhotoLogo).setImage(f);
        }
    }//GEN-LAST:event_BtnCariLogoActionPerformed

    private void YesNoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_YesNoItemStateChanged
        if (YesNo.getSelectedIndex() == 0) {
            BtnCariGb.setEnabled(true);
        } else {
            BtnCariGb.setEnabled(false);
            EGb.setText("./setting/wallpaper.jpg");
        }
        runBackground(() ->tampil());
    }//GEN-LAST:event_YesNoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgSetAplikasi dialog = new DlgSetAplikasi(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.TextBox Almt;
    private widget.ComboBox BatasEdit2x24jam;
    private widget.Button BtnBatal;
    private widget.Button BtnCariGb;
    private widget.Button BtnCariLogo;
    private widget.Button BtnHapus;
    private widget.Button BtnKeluar;
    private widget.Button BtnSimpan;
    private widget.TextBox EGb;
    private widget.TextBox ELogo;
    private widget.TextBox Email;
    private widget.TextBox Kontak;
    private widget.TextBox Kota;
    private widget.TextBox Nm;
    private java.awt.Canvas PhotoGambar;
    private java.awt.Canvas PhotoLogo;
    private widget.TextBox Propinsi;
    private widget.ScrollPane Scroll;
    private widget.ComboBox SistemImportKoding;
    private widget.ComboBox YesNo;
    private widget.InternalFrame internalFrame1;
    private widget.TextBox kdPPKApotekOnline;
    private widget.TextBox kdPPKBPJS;
    private widget.TextBox kdPPKInhealth;
    private widget.TextBox kdPPKKemenkes;
    private widget.Label label13;
    private widget.Label label14;
    private widget.Label label34;
    private widget.Label label35;
    private widget.Label label36;
    private widget.Label label37;
    private widget.Label label38;
    private widget.Label label39;
    private widget.Label label40;
    private widget.Label label41;
    private widget.Label label42;
    private widget.Label label43;
    private widget.Label label44;
    private widget.Label label45;
    private widget.Label label46;
    private widget.panelGlass panelGlass1;
    private widget.panelisi panelisi1;
    private widget.ScrollPane scrollPane2;
    private widget.ScrollPane scrollPane3;
    private widget.Table tbAdmin;
    // End of variables declaration//GEN-END:variables

    private void tampil() {
        Valid.tabelKosong(tabMode);
        try (ResultSet rs = koneksi.createStatement().executeQuery(
            "select nama_instansi, alamat_instansi, kabupaten, propinsi, aktifkan, to_base64(wallpaper) as wallpaper, " +
            "kontak, email, to_base64(logo) as logo, kode_ppk, kode_ppkapotek, kode_ppkinhealth, kode_ppkkemenkes, " +
            "pemberlakuan_2x24_jam, sistem_import_koding from setting"
        )) {
            if (rs.next()) {
                tabMode.addRow(new Object[] {
                    rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5),
                    rs.getString(6), rs.getString(7), rs.getString(8), rs.getString(9), rs.getString(10),
                    rs.getString(11), rs.getString(12), rs.getString(13), rs.getString(14), rs.getString(15)
                });
            }
        } catch (Exception e) {
            System.out.println("Notif : " + e);
        }
    }

    private void getData() {
        int row = tbAdmin.getSelectedRow();
        if (row != -1) {
            Nm.setText((String) tbAdmin.getValueAt(row, 0));
            Almt.setText((String) tbAdmin.getValueAt(row, 1));
            Kota.setText((String) tbAdmin.getValueAt(row, 2));
            Propinsi.setText((String) tbAdmin.getValueAt(row, 3));
            YesNo.setSelectedItem((String) tbAdmin.getValueAt(row, 4));
            Kontak.setText((String) tbAdmin.getValueAt(row, 6));
            Email.setText((String) tbAdmin.getValueAt(row, 7));
            kdPPKBPJS.setText((String) tbAdmin.getValueAt(row, 9));
            kdPPKApotekOnline.setText((String) tbAdmin.getValueAt(row, 10));
            kdPPKInhealth.setText((String) tbAdmin.getValueAt(row, 11));
            kdPPKKemenkes.setText((String) tbAdmin.getValueAt(row, 12));
            BatasEdit2x24jam.setSelectedItem((String) tbAdmin.getValueAt(row, 13));
            SistemImportKoding.setSelectedItem((String) tbAdmin.getValueAt(row, 14));
            try {
                ((Painter) PhotoGambar).fromBase64((String) tbAdmin.getValueAt(row, 5));
                ((Painter) PhotoLogo).fromBase64((String) tbAdmin.getValueAt(row, 8));
            } catch (Exception e) {
                System.out.println("Notif : " + e);
            }
        }
    }

    public void emptTeks() {
        Nm.setText("");
        Almt.setText("");
        Kota.setText("");
        Propinsi.setText("");
        Kontak.setText("");
        Email.setText("");
        YesNo.setSelectedItem("No");
        BatasEdit2x24jam.setSelectedIndex(0);
        SistemImportKoding.setSelectedIndex(2);
        kdPPKBPJS.setText("");
        kdPPKInhealth.setText("");
        kdPPKKemenkes.setText("");
        kdPPKApotekOnline.setText("");
        EGb.setText("");
        ELogo.setText("");
        ((Painter) PhotoGambar).setImage("");
        ((Painter) PhotoLogo).setImage("");
        Nm.requestFocus();
    }

    static class Painter extends Canvas {

        private BufferedImage image = null;

        public void setImage(String file) {
            try {
                if (file == null) return;
                image = ImageIO.read(new File(file));
                repaint();
            } catch (IOException e) {
            }
        }

        public void fromBase64(String base64) throws Exception {
            try (ByteArrayInputStream bits = new ByteArrayInputStream(Base64.decodeBase64(base64))) {
                image = ImageIO.read(bits);
                repaint();
            }
        }

        @Override
        public void paint(Graphics g) {
            if (image == null) super.paint(g);

            try {
                double d = image.getHeight(this) / this.getHeight();
                double w = image.getWidth(this) / d;
                double x = this.getWidth() / 2 - w / 2;
                g.drawImage(image, (int) x, 0, (int) (w), this.getHeight(), this);
            } catch (Exception e) {
                super.paint(g);
            }
        }
    }
    private void runBackground(Runnable task) {
        if (ceksukses) return;
        if (executor.isShutdown() || executor.isTerminated()) return;
        if (!isDisplayable()) return;

        ceksukses = true;
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));

        try {
            executor.submit(() -> {
                try {
                    task.run();
                } finally {
                    ceksukses = false;
                    SwingUtilities.invokeLater(() -> {
                        if (isDisplayable()) {
                            setCursor(Cursor.getDefaultCursor());
                        }
                    });
                }
            });
        } catch (RejectedExecutionException ex) {
            ceksukses = false;
        }
    }

    @Override
    public void dispose() {
        executor.shutdownNow();
        super.dispose();
    }
}
