/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgPenyakit.java
 *
 * Created on May 23, 2010, 12:57:16 AM
 */

package rekammedis;

import fungsi.WarnaTable;
import fungsi.batasInput;
import fungsi.koneksiDB;
import fungsi.validasi;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.StringJoiner;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.RejectedExecutionException;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author dosen
 */
public final class RMCariPemeriksaan extends javax.swing.JDialog {
    private final DefaultTableModel tabMode;
    private validasi Valid=new validasi();
    private Connection koneksi=koneksiDB.condb();
    private PreparedStatement ps;
    private ResultSet rs;
    private String norawat="";
    private int z=0;
    private final ExecutorService executor = Executors.newSingleThreadExecutor();
    private volatile boolean ceksukses = false;
    /** Creates new form DlgPenyakit
     * @param parent
     * @param modal */
    public RMCariPemeriksaan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocation(10,2);
        setSize(656,250);

        Object[] row={"Tanggal","Jam","Pemeriksaan","Asal"};
        tabMode=new DefaultTableModel(null,row){
              @Override public boolean isCellEditable(int rowIndex, int colIndex){return false;}
        };
        tbKamar.setModel(tabMode);
        //tbPenyakit.setDefaultRenderer(Object.class, new WarnaTable(panelJudul.getBackground(),tbPenyakit.getBackground()));
        tbKamar.setPreferredScrollableViewportSize(new Dimension(500,500));
        tbKamar.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        for (z= 0; z < 4; z++) {
            TableColumn column = tbKamar.getColumnModel().getColumn(z);
            if(z==0){
                column.setPreferredWidth(65);
            }else if(z==1){
                column.setPreferredWidth(50);
            }else if(z==2){
                column.setPreferredWidth(1500);
            }else if(z==3){
                column.setPreferredWidth(250);
            }
        }
        tbKamar.setDefaultRenderer(Object.class, new WarnaTable());
        TCari.setDocument(new batasInput((byte)100).getKata(TCari));
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        Scroll = new widget.ScrollPane();
        tbKamar = new widget.Table();
        panelisi3 = new widget.panelisi();
        label9 = new widget.Label();
        TCari = new widget.TextBox();
        BtnCari = new widget.Button();
        BtnAll = new widget.Button();
        label10 = new widget.Label();
        LCount = new widget.Label();
        BtnKeluar = new widget.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Riwayat Pemeriksaan ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        Scroll.setName("Scroll"); // NOI18N
        Scroll.setOpaque(true);

        tbKamar.setAutoCreateRowSorter(true);
        tbKamar.setName("tbKamar"); // NOI18N
        tbKamar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbKamarMouseClicked(evt);
            }
        });
        tbKamar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbKamarKeyPressed(evt);
            }
        });
        Scroll.setViewportView(tbKamar);

        internalFrame1.add(Scroll, java.awt.BorderLayout.CENTER);

        panelisi3.setName("panelisi3"); // NOI18N
        panelisi3.setPreferredSize(new java.awt.Dimension(100, 43));
        panelisi3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 4, 9));

        label9.setText("Key Word :");
        label9.setName("label9"); // NOI18N
        label9.setPreferredSize(new java.awt.Dimension(68, 23));
        panelisi3.add(label9);

        TCari.setName("TCari"); // NOI18N
        TCari.setPreferredSize(new java.awt.Dimension(300, 23));
        TCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TCariKeyPressed(evt);
            }
        });
        panelisi3.add(TCari);

        BtnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        BtnCari.setMnemonic('1');
        BtnCari.setToolTipText("Alt+1");
        BtnCari.setName("BtnCari"); // NOI18N
        BtnCari.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariActionPerformed(evt);
            }
        });
        BtnCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnCariKeyPressed(evt);
            }
        });
        panelisi3.add(BtnCari);

        BtnAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Search-16x16.png"))); // NOI18N
        BtnAll.setMnemonic('2');
        BtnAll.setToolTipText("2Alt+2");
        BtnAll.setName("BtnAll"); // NOI18N
        BtnAll.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAllActionPerformed(evt);
            }
        });
        BtnAll.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnAllKeyPressed(evt);
            }
        });
        panelisi3.add(BtnAll);

        label10.setText("Record :");
        label10.setName("label10"); // NOI18N
        label10.setPreferredSize(new java.awt.Dimension(60, 23));
        panelisi3.add(label10);

        LCount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LCount.setText("0");
        LCount.setName("LCount"); // NOI18N
        LCount.setPreferredSize(new java.awt.Dimension(50, 23));
        panelisi3.add(LCount);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('4');
        BtnKeluar.setToolTipText("Alt+4");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        panelisi3.add(BtnKeluar);

        internalFrame1.add(panelisi3, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void TCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCariKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            BtnCariActionPerformed(null);
        }else if(evt.getKeyCode()==KeyEvent.VK_PAGE_DOWN){
            BtnCari.requestFocus();
        }else if(evt.getKeyCode()==KeyEvent.VK_PAGE_UP){
            BtnKeluar.requestFocus();
        }else if(evt.getKeyCode()==KeyEvent.VK_UP){
            tbKamar.requestFocus();
        }
    }//GEN-LAST:event_TCariKeyPressed

    private void BtnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariActionPerformed
        runBackground(() ->tampil());
    }//GEN-LAST:event_BtnCariActionPerformed

    private void BtnCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnCariKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnCariActionPerformed(null);
        }else{
            Valid.pindah(evt, TCari, BtnAll);
        }
    }//GEN-LAST:event_BtnCariKeyPressed

    private void BtnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAllActionPerformed
        TCari.setText("");
        runBackground(() ->tampil());
    }//GEN-LAST:event_BtnAllActionPerformed

    private void BtnAllKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnAllKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnAllActionPerformed(null);
        }else{
            Valid.pindah(evt, BtnCari, TCari);
        }
    }//GEN-LAST:event_BtnAllKeyPressed

    private void tbKamarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKamarMouseClicked
        if(tabMode.getRowCount()!=0){
            if(evt.getClickCount()==2){
                dispose();
            }
        }
    }//GEN-LAST:event_tbKamarMouseClicked

    private void tbKamarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbKamarKeyPressed
        if(tabMode.getRowCount()!=0){
            if(evt.getKeyCode()==KeyEvent.VK_SPACE){
                dispose();
            }else if(evt.getKeyCode()==KeyEvent.VK_SHIFT){
                TCari.setText("");
                TCari.requestFocus();
            }
        }
    }//GEN-LAST:event_tbKamarKeyPressed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        emptTeks();
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        runBackground(() ->tampil());
        if(koneksiDB.CARICEPAT().equals("aktif")){
            TCari.getDocument().addDocumentListener(new javax.swing.event.DocumentListener(){
                @Override
                public void insertUpdate(DocumentEvent e) {
                    if(TCari.getText().length()>2){
                        runBackground(() ->tampil());
                    }
                }
                @Override
                public void removeUpdate(DocumentEvent e) {
                    if(TCari.getText().length()>2){
                        runBackground(() ->tampil());
                    }
                }
                @Override
                public void changedUpdate(DocumentEvent e) {
                    if(TCari.getText().length()>2){
                        runBackground(() ->tampil());
                    }
                }
            });
        }
    }//GEN-LAST:event_formWindowOpened

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            RMCariPemeriksaan dialog = new RMCariPemeriksaan(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnAll;
    private widget.Button BtnCari;
    private widget.Button BtnKeluar;
    private widget.Label LCount;
    private widget.ScrollPane Scroll;
    private widget.TextBox TCari;
    private widget.InternalFrame internalFrame1;
    private widget.Label label10;
    private widget.Label label9;
    private widget.panelisi panelisi3;
    private widget.Table tbKamar;
    // End of variables declaration//GEN-END:variables

    public void tampil() {
        Valid.tabelKosong(tabMode);
        try {
            try (PreparedStatement ps = koneksi.prepareStatement(
                "select date(penilaian_medis_igd.tanggal) as tgl_perawatan, time(penilaian_medis_igd.tanggal) as jam_rawat, " +
                "if(trim(penilaian_medis_igd.suhu) = '', '', trim(penilaian_medis_igd.suhu)) as suhu, " +
                "if(trim(penilaian_medis_igd.td) = '', '', trim(penilaian_medis_igd.td)) as td, " +
                "if(trim(penilaian_medis_igd.nadi) = '', '', trim(penilaian_medis_igd.nadi)) as nadi, " +
                "if(trim(penilaian_medis_igd.rr) = '', '', trim(penilaian_medis_igd.rr)) as rr, " +
                "if(trim(penilaian_medis_igd.tb) = '', '', trim(penilaian_medis_igd.tb)) as tb, " +
                "if(trim(penilaian_medis_igd.bb) = '', '', trim(penilaian_medis_igd.bb)) as bb, " +
                "if(trim(penilaian_medis_igd.spo) = '', '', trim(penilaian_medis_igd.spo)) as spo, " +
                "if(trim(penilaian_medis_igd.gcs) = '', '', trim(penilaian_medis_igd.gcs)) as gcs, " +
                "if(trim(penilaian_medis_igd.kesadaran) = '', '', trim(penilaian_medis_igd.kesadaran)) as kesadaran, " +
                "if(trim(penilaian_medis_igd.ket_fisik) = '', '', trim(penilaian_medis_igd.ket_fisik)) as ket_fisik " +
                "from penilaian_medis_igd where penilaian_medis_igd.no_rawat = ? " + (TCari.getText().isBlank() ? "" :
                "and (penilaian_medis_igd.tanggal like ? or penilaian_medis_igd.ket_fisik like ?) ") +
                "order by penilaian_medis_igd.tanggal"
            )) {
                int p = 0;
                ps.setString(++p, norawat);
                if (!TCari.getText().isBlank()) {
                    ps.setString(++p, "%" + TCari.getText().trim() + "%");
                    ps.setString(++p, "%" + TCari.getText().trim() + "%");
                }
                try (ResultSet rs = ps.executeQuery()) {
                    while (rs.next()) {
                        StringJoiner sj = new StringJoiner("; ");
                        sj.add(rs.getString("ket_fisik"));
                        if (!rs.getString("suhu").isBlank())
                            sj.add("Suhu = " + rs.getString("suhu").trim() + "°C");
                        if (!rs.getString("td").isBlank())
                            sj.add("Tensi = " + rs.getString("td").trim() + "mmHg");
                        if (!rs.getString("bb").isBlank())
                            sj.add("BB = " + rs.getString("bb").trim() + " kg");
                        if (!rs.getString("tb").isBlank())
                            sj.add("TB = " + rs.getString("tb").trim() + " cm");
                        if (!rs.getString("rr").isBlank())
                            sj.add("RR = " + rs.getString("rr").trim() + "x/menit");
                        if (!rs.getString("nadi").isBlank())
                            sj.add("Nadi = " + rs.getString("nadi").trim() + "x/menit");
                        if (!rs.getString("spo").isBlank())
                            sj.add("SpO2 = " + rs.getString("spo").trim() + "%");
                        if (!rs.getString("gcs").isBlank())
                            sj.add("GCS = " + rs.getString("gcs").trim());
                        if (!rs.getString("kesadaran").isBlank() && !rs.getString("kesadaran").trim().equals("-"))
                            sj.add("Kesadaran = " + rs.getString("kesadaran").trim());
                        tabMode.addRow(new String[] {rs.getString(1), rs.getString(2), sj.toString(), "Awal Medis IGD"});
                    }
                }
            }

            try (PreparedStatement ps = koneksi.prepareStatement(
                "select pemeriksaan_ralan.tgl_perawatan, pemeriksaan_ralan.jam_rawat, " +
                "if(trim(pemeriksaan_ralan.suhu_tubuh) = '', '', pemeriksaan_ralan.suhu_tubuh) as suhu_tubuh, " +
                "if(trim(pemeriksaan_ralan.tensi) = '', '', pemeriksaan_ralan.tensi) as tensi, " +
                "if(trim(pemeriksaan_ralan.nadi) = '', '', pemeriksaan_ralan.nadi) as nadi, " +
                "if(trim(pemeriksaan_ralan.respirasi) = '', '', pemeriksaan_ralan.respirasi) as respirasi, " +
                "if(trim(pemeriksaan_ralan.tinggi) = '', '', pemeriksaan_ralan.tinggi) as tinggi, " +
                "if(trim(pemeriksaan_ralan.berat) = '', '', pemeriksaan_ralan.berat) as berat, " +
                "if(trim(pemeriksaan_ralan.spo2) = '', '', pemeriksaan_ralan.spo2) as spo2, " +
                "if(trim(pemeriksaan_ralan.gcs) = '', '', pemeriksaan_ralan.gcs) as gcs, " +
                "if(trim(pemeriksaan_ralan.kesadaran) = '', '', pemeriksaan_ralan.kesadaran) as kesadaran, " +
                "trim(pemeriksaan_ralan.pemeriksaan) as pemeriksaan from pemeriksaan_ralan where pemeriksaan_ralan.no_rawat = ? " +
                (TCari.getText().isBlank() ? "" : "and (pemeriksaan_ralan.tgl_perawatan like ? or pemeriksaan_ralan.pemeriksaan like ?) ") +
                "order by pemeriksaan_ralan.tgl_perawatan, pemeriksaan_ralan.jam_rawat"
            )) {
                int p = 0;
                ps.setString(++p, norawat);
                if (!TCari.getText().isBlank()) {
                    ps.setString(++p, "%" + TCari.getText().trim() + "%");
                    ps.setString(++p, "%" + TCari.getText().trim() + "%");
                }
                try (ResultSet rs = ps.executeQuery()) {
                    while (rs.next()) {
                        StringJoiner sj = new StringJoiner("; ");
                        sj.add(rs.getString("pemeriksaan"));
                        if (!rs.getString("suhu_tubuh").isBlank())
                            sj.add("Suhu = " + rs.getString("suhu_tubuh").trim() + "°C");
                        if (!rs.getString("tensi").isBlank())
                            sj.add("Tensi = " + rs.getString("tensi").trim() + "mmHg");
                        if (!rs.getString("berat").isBlank())
                            sj.add("BB = " + rs.getString("berat").trim() + " kg");
                        if (!rs.getString("tinggi").isBlank())
                            sj.add("TB = " + rs.getString("tinggi").trim() + " cm");
                        if (!rs.getString("respirasi").isBlank())
                            sj.add("RR = " + rs.getString("respirasi").trim() + "x/menit");
                        if (!rs.getString("nadi").isBlank())
                            sj.add("Nadi = " + rs.getString("nadi").trim() + "x/menit");
                        if (!rs.getString("spo2").isBlank())
                            sj.add("SpO2 = " + rs.getString("spo2").trim() + "%");
                        if (!rs.getString("gcs").isBlank())
                            sj.add("GCS = " + rs.getString("gcs").trim());
                        if (!rs.getString("kesadaran").isBlank() && !rs.getString("kesadaran").trim().equals("-"))
                            sj.add("Kesadaran = " + rs.getString("kesadaran").trim());
                        tabMode.addRow(new String[] {rs.getString(1), rs.getString(2), sj.toString(), "Pemeriksaan Ralan"});
                    }
                }
            }

            try (PreparedStatement ps = koneksi.prepareStatement(
                "select pemeriksaan_ranap.tgl_perawatan, pemeriksaan_ranap.jam_rawat, " +
                "if(trim(pemeriksaan_ranap.suhu_tubuh) = '', '', pemeriksaan_ranap.suhu_tubuh) as suhu_tubuh, " +
                "if(trim(pemeriksaan_ranap.tensi) = '', '', pemeriksaan_ranap.tensi) as tensi, " +
                "if(trim(pemeriksaan_ranap.nadi) = '', '', pemeriksaan_ranap.nadi) as nadi, " +
                "if(trim(pemeriksaan_ranap.respirasi) = '', '', pemeriksaan_ranap.respirasi) as respirasi, " +
                "if(trim(pemeriksaan_ranap.tinggi) = '', '', pemeriksaan_ranap.tinggi) as tinggi, " +
                "if(trim(pemeriksaan_ranap.berat) = '', '', pemeriksaan_ranap.berat) as berat, " +
                "if(trim(pemeriksaan_ranap.spo2) = '', '', pemeriksaan_ranap.spo2) as spo2, " +
                "if(trim(pemeriksaan_ranap.gcs) = '', '', pemeriksaan_ranap.gcs) as gcs, " +
                "if(trim(pemeriksaan_ranap.kesadaran) = '', '', pemeriksaan_ranap.kesadaran) as kesadaran, " +
                "trim(pemeriksaan_ranap.pemeriksaan) as pemeriksaan from pemeriksaan_ranap where pemeriksaan_ranap.no_rawat = ? " +
                (TCari.getText().isBlank() ? "" : "and (pemeriksaan_ranap.tgl_perawatan like ? or pemeriksaan_ranap.pemeriksaan like ?) ") +
                "order by pemeriksaan_ranap.tgl_perawatan, pemeriksaan_ranap.jam_rawat"
            )) {
                int p = 0;
                ps.setString(++p, norawat);
                if (!TCari.getText().isBlank()) {
                    ps.setString(++p, "%" + TCari.getText().trim() + "%");
                    ps.setString(++p, "%" + TCari.getText().trim() + "%");
                }
                try (ResultSet rs = ps.executeQuery()) {
                    while (rs.next()) {
                        StringJoiner sj = new StringJoiner("; ");
                        sj.add(rs.getString("pemeriksaan"));
                        if (!rs.getString("suhu_tubuh").isBlank())
                            sj.add("Suhu = " + rs.getString("suhu_tubuh").trim() + "°C");
                        if (!rs.getString("tensi").isBlank())
                            sj.add("Tensi = " + rs.getString("tensi").trim() + "mmHg");
                        if (!rs.getString("berat").isBlank())
                            sj.add("BB = " + rs.getString("berat").trim() + " kg");
                        if (!rs.getString("tinggi").isBlank())
                            sj.add("TB = " + rs.getString("tinggi").trim() + " cm");
                        if (!rs.getString("respirasi").isBlank())
                            sj.add("RR = " + rs.getString("respirasi").trim() + "x/menit");
                        if (!rs.getString("nadi").isBlank())
                            sj.add("Nadi = " + rs.getString("nadi").trim() + "x/menit");
                        if (!rs.getString("spo2").isBlank())
                            sj.add("SpO2 = " + rs.getString("spo2").trim() + "%");
                        if (!rs.getString("gcs").isBlank())
                            sj.add("GCS = " + rs.getString("gcs").trim());
                        if (!rs.getString("kesadaran").isBlank() && !rs.getString("kesadaran").trim().equals("-"))
                            sj.add("Kesadaran = " + rs.getString("kesadaran").trim());
                        tabMode.addRow(new String[] {rs.getString(1), rs.getString(2), sj.toString(), "Pemeriksaan Ranap"});
                    }
                }
            }
        } catch (Exception e) {
            System.out.println("Notif : " + e);
        }
        LCount.setText("" + tabMode.getRowCount());
    }

    public void emptTeks() {
        TCari.requestFocus();
    }

    public void setNoRawat(String norawat){
        this.norawat=norawat;
    }

    public JTable getTable(){
        return tbKamar;
    }

    private void runBackground(Runnable task) {
        if (ceksukses) return;
        if (executor.isShutdown() || executor.isTerminated()) return;
        if (!isDisplayable()) return;

        ceksukses = true;
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));

        try {
            executor.submit(() -> {
                try {
                    task.run();
                } finally {
                    ceksukses = false;
                    SwingUtilities.invokeLater(() -> {
                        if (isDisplayable()) {
                            setCursor(Cursor.getDefaultCursor());
                        }
                    });
                }
            });
        } catch (RejectedExecutionException ex) {
            ceksukses = false;
        }
    }

    @Override
    public void dispose() {
        executor.shutdownNow();
        super.dispose();
    }
}
