/*
  Dilarang keras menggandakan/mengcopy/menyebarkan/membajak/mendecompile
  Software ini dalam bentuk apapun tanpa seijin pembuat software
  (Khanza.Soft Media). Bagi yang sengaja membajak softaware ini ta
  npa ijin, kami sumpahi sial 1000 turunan, miskin sampai 500 turu
  nan. Selalu mendapat kecelakaan sampai 400 turunan. Anak pertama
  nya cacat tidak punya kaki sampai 300 turunan. Susah cari jodoh
  sampai umur 50 tahun sampai 200 turunan. Ya Alloh maafkan kami
  karena telah berdoa buruk, semua ini kami lakukan karena kami ti
  dak pernah rela karya kami dibajak tanpa ijin.
 */
package bridging;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import fungsi.WarnaTable;
import fungsi.akses;
import fungsi.batasInput;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.StringJoiner;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingWorker;
import javax.swing.event.DocumentEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;
import org.springframework.web.client.HttpClientErrorException;
import org.springframework.web.client.HttpServerErrorException;

/**
 *
 * @author dosen
 */
public final class ApotekBPJSRiwayatPelayananObatSMC extends javax.swing.JDialog {
    private final DefaultTableModel tabMode;
    private final validasi Valid = new validasi();
    private final sekuel Sequel = new sekuel();
    private final ApiApotekBPJS api = new ApiApotekBPJS();
    private volatile boolean ceksukses = false;

    /**
     * Creates new form DlgKamar
     *
     * @param parent
     * @param modal
     */
    public ApotekBPJSRiwayatPelayananObatSMC(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        tabMode = new DefaultTableModel(null, new String[] {
            "No.SJP", "Tgl.Pelayanan", "No.Resep", "Kode Obat", "Nama Obat", "Jml."
        }) {
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                if (columnIndex == 5) {
                    return Double.class;
                }

                return String.class;
            }
        };
        tbKamar.setModel(tabMode);

        //tbKamar.setDefaultRenderer(Object.class, new WarnaTable(panelJudul.getBackground(),tbKamar.getBackground()));
        tbKamar.setPreferredScrollableViewportSize(new Dimension(500, 500));
        tbKamar.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        for (int i = 0; i < 6; i++) {
            TableColumn column = tbKamar.getColumnModel().getColumn(i);
            if (i == 0) {
                column.setPreferredWidth(132);
            } else if (i == 1) {
                column.setPreferredWidth(80);
            } else if (i == 2) {
                column.setPreferredWidth(64);
            } else if (i == 3) {
                column.setPreferredWidth(83);
            } else if (i == 4) {
                column.setPreferredWidth(300);
            } else if (i == 5) {
                column.setPreferredWidth(50);
            }
        }

        tbKamar.setDefaultRenderer(Object.class, new WarnaTable());

        NoKaBPJS.setDocument(new batasInput((byte) 100).getKata(NoKaBPJS));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        panelisi3 = new widget.panelisi();
        label18 = new widget.Label();
        namaPasien = new widget.TextBox();
        label11 = new widget.Label();
        tglLahir = new widget.TextBox();
        Scroll = new widget.ScrollPane();
        tbKamar = new widget.Table();
        panelGlass6 = new widget.panelisi();
        jLabel16 = new widget.Label();
        NoKaBPJS = new widget.TextBox();
        BtnCari = new widget.Button();
        jLabel18 = new widget.Label();
        TanggalAwal = new widget.Tanggal();
        jLabel21 = new widget.Label();
        TanggalAkhir = new widget.Tanggal();
        BtnPrint = new widget.Button();
        BtnKeluar = new widget.Button();
        jLabel7 = new widget.Label();
        LCount = new widget.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(null);
        setIconImages(null);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Riwayat Pelayanan Obat Apotek BPJS ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        panelisi3.setName("panelisi3"); // NOI18N
        panelisi3.setPreferredSize(new java.awt.Dimension(89, 44));
        panelisi3.setLayout(null);

        label18.setText("Nama Pasien :");
        label18.setName("label18"); // NOI18N
        label18.setPreferredSize(new java.awt.Dimension(60, 23));
        panelisi3.add(label18);
        label18.setBounds(0, 10, 90, 23);

        namaPasien.setEditable(false);
        namaPasien.setName("namaPasien"); // NOI18N
        namaPasien.setPreferredSize(new java.awt.Dimension(207, 23));
        panelisi3.add(namaPasien);
        namaPasien.setBounds(93, 10, 400, 23);

        label11.setText("Tgl. Lahir :");
        label11.setName("label11"); // NOI18N
        label11.setPreferredSize(new java.awt.Dimension(70, 23));
        panelisi3.add(label11);
        label11.setBounds(496, 10, 70, 23);

        tglLahir.setEditable(false);
        tglLahir.setName("tglLahir"); // NOI18N
        tglLahir.setPreferredSize(new java.awt.Dimension(207, 23));
        panelisi3.add(tglLahir);
        tglLahir.setBounds(569, 10, 84, 23);

        internalFrame1.add(panelisi3, java.awt.BorderLayout.PAGE_START);

        Scroll.setName("Scroll"); // NOI18N
        Scroll.setOpaque(true);

        tbKamar.setAutoCreateRowSorter(true);
        tbKamar.setName("tbKamar"); // NOI18N
        tbKamar.setRowSorter(null);
        Scroll.setViewportView(tbKamar);

        internalFrame1.add(Scroll, java.awt.BorderLayout.CENTER);

        panelGlass6.setName("panelGlass6"); // NOI18N
        panelGlass6.setPreferredSize(new java.awt.Dimension(44, 54));
        panelGlass6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        jLabel16.setText("No. Kartu :");
        jLabel16.setName("jLabel16"); // NOI18N
        jLabel16.setPreferredSize(new java.awt.Dimension(54, 23));
        panelGlass6.add(jLabel16);

        NoKaBPJS.setName("NoKaBPJS"); // NOI18N
        NoKaBPJS.setPreferredSize(new java.awt.Dimension(200, 23));
        NoKaBPJS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NoKaBPJSKeyPressed(evt);
            }
        });
        panelGlass6.add(NoKaBPJS);

        BtnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        BtnCari.setMnemonic('6');
        BtnCari.setToolTipText("Alt+6");
        BtnCari.setName("BtnCari"); // NOI18N
        BtnCari.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariActionPerformed(evt);
            }
        });
        BtnCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnCariKeyPressed(evt);
            }
        });
        panelGlass6.add(BtnCari);

        jLabel18.setText("Tgl. :");
        jLabel18.setName("jLabel18"); // NOI18N
        jLabel18.setPreferredSize(new java.awt.Dimension(30, 23));
        panelGlass6.add(jLabel18);

        TanggalAwal.setForeground(new java.awt.Color(50, 70, 50));
        TanggalAwal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "28-04-2026" }));
        TanggalAwal.setDisplayFormat("dd-MM-yyyy");
        TanggalAwal.setName("TanggalAwal"); // NOI18N
        TanggalAwal.setOpaque(false);
        TanggalAwal.setPreferredSize(new java.awt.Dimension(95, 23));
        panelGlass6.add(TanggalAwal);

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("s.d.");
        jLabel21.setName("jLabel21"); // NOI18N
        jLabel21.setPreferredSize(new java.awt.Dimension(23, 23));
        panelGlass6.add(jLabel21);

        TanggalAkhir.setForeground(new java.awt.Color(50, 70, 50));
        TanggalAkhir.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "28-04-2026" }));
        TanggalAkhir.setDisplayFormat("dd-MM-yyyy");
        TanggalAkhir.setName("TanggalAkhir"); // NOI18N
        TanggalAkhir.setOpaque(false);
        TanggalAkhir.setPreferredSize(new java.awt.Dimension(95, 23));
        panelGlass6.add(TanggalAkhir);

        BtnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/b_print.png"))); // NOI18N
        BtnPrint.setMnemonic('T');
        BtnPrint.setText("Cetak");
        BtnPrint.setToolTipText("Alt+T");
        BtnPrint.setName("BtnPrint"); // NOI18N
        BtnPrint.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrintActionPerformed(evt);
            }
        });
        panelGlass6.add(BtnPrint);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelGlass6.add(BtnKeluar);

        jLabel7.setText("Record :");
        jLabel7.setName("jLabel7"); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(65, 23));
        panelGlass6.add(jLabel7);

        LCount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LCount.setText("0");
        LCount.setName("LCount"); // NOI18N
        LCount.setPreferredSize(new java.awt.Dimension(50, 23));
        panelGlass6.add(LCount);

        internalFrame1.add(panelGlass6, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            dispose();
        } else {
            Valid.pindah(evt, BtnPrint, BtnKeluar);
        }
    }//GEN-LAST:event_BtnKeluarKeyPressed

    private void BtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrintActionPerformed
        if (tabMode.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Maaf, data sudah habis. Tidak ada data yang bisa anda print...!!!!");
            //TCari.requestFocus();
        } else if (tabMode.getRowCount() != 0) {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            Sequel.queryu("delete from temporary where temp37='" + akses.getalamatip() + "'");
            for (int i = 0; i < tabMode.getRowCount(); i++) {
                Sequel.menyimpan("temporary", "'" + i + "','" +
                    tabMode.getValueAt(i, 0).toString() + "','" +
                    tabMode.getValueAt(i, 1).toString() + "','" +
                    tabMode.getValueAt(i, 2).toString() + "','" +
                    tabMode.getValueAt(i, 3).toString() + "','" +
                    tabMode.getValueAt(i, 4).toString() + "','" +
                    tabMode.getValueAt(i, 5).toString() + "','" +
                    tabMode.getValueAt(i, 6).toString() + "','" +
                    tabMode.getValueAt(i, 7).toString() + "','" +
                    tabMode.getValueAt(i, 8).toString() + "','" +
                    tabMode.getValueAt(i, 9).toString() + "','" +
                    tabMode.getValueAt(i, 10).toString() + "','" +
                    tabMode.getValueAt(i, 11).toString() + "','" +
                    tabMode.getValueAt(i, 12).toString() + "','" +
                    tabMode.getValueAt(i, 14).toString() + "','" +
                    tabMode.getValueAt(i, 15).toString() + "','" +
                    tabMode.getValueAt(i, 16).toString() + "','','','','','','','','','','','','','','','','','','','','','" + akses.getalamatip() + "'", "Daftar Pelayanan Obat Apotek BPJS");
            }

            Map<String, Object> param = new HashMap<>();
            param.put("namars", akses.getnamars());
            param.put("alamatrs", akses.getalamatrs());
            param.put("kotars", akses.getkabupatenrs());
            param.put("propinsirs", akses.getpropinsirs());
            //param.put("peserta","No.Peserta : "+NoKartu.getText()+" Nama Peserta : "+NamaPasien.getText());
            param.put("kontakrs", akses.getkontakrs());
            param.put("emailrs", akses.getemailrs());
            param.put("logo", Sequel.cariGambar("select setting.logo from setting"));
            Valid.MyReportqry("rptApotekBPJSDaftarPelayananKlaim.jasper", "report", "::[ Riwayat Pelayanan Obat Apotek BPJS ]::", "select * from temporary where temporary.temp37='" + akses.getalamatip() + "' order by temporary.no", param);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnPrintActionPerformed

    private void NoKaBPJSKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NoKaBPJSKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            BtnCariActionPerformed(null);
        } else {
            Valid.pindahSmc(evt, tglLahir, BtnCari);
        }
    }//GEN-LAST:event_NoKaBPJSKeyPressed

    private void BtnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariActionPerformed
        tampilSmc();
    }//GEN-LAST:event_BtnCariActionPerformed

    private void BtnCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnCariKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            BtnCariActionPerformed(null);
        } else {
            Valid.pindahSmc(evt, NoKaBPJS, TanggalAwal);
        }
    }//GEN-LAST:event_BtnCariKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (koneksiDB.CARICEPAT().equals("aktif")) {
            NoKaBPJS.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
                @Override
                public void insertUpdate(DocumentEvent e) {
                    if (NoKaBPJS.getText().length() > 2) {
                        tampilSmc();
                    }
                }

                @Override
                public void removeUpdate(DocumentEvent e) {
                    if (NoKaBPJS.getText().length() > 2) {
                        tampilSmc();
                    }
                }

                @Override
                public void changedUpdate(DocumentEvent e) {
                    if (NoKaBPJS.getText().length() > 2) {
                        tampilSmc();
                    }
                }
            });
        }

        tampilSmc();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            ApotekBPJSRiwayatPelayananObatSMC dialog = new ApotekBPJSRiwayatPelayananObatSMC(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnCari;
    private widget.Button BtnKeluar;
    private widget.Button BtnPrint;
    private widget.Label LCount;
    private widget.TextBox NoKaBPJS;
    private widget.ScrollPane Scroll;
    private widget.Tanggal TanggalAkhir;
    private widget.Tanggal TanggalAwal;
    private widget.InternalFrame internalFrame1;
    private widget.Label jLabel16;
    private widget.Label jLabel18;
    private widget.Label jLabel21;
    private widget.Label jLabel7;
    private widget.Label label11;
    private widget.Label label18;
    private widget.TextBox namaPasien;
    private widget.panelisi panelGlass6;
    private widget.panelisi panelisi3;
    private widget.Table tbKamar;
    private widget.TextBox tglLahir;
    // End of variables declaration//GEN-END:variables

    public void setNoKartu(String nokartu, String tglawal, String tglakhir) {
        NoKaBPJS.setText(nokartu);
        Valid.setTglSmc(TanggalAwal, tglawal);
        Valid.setTglSmc(TanggalAkhir, tglakhir);
    }

    private void tampilSmc() {
        if (!NoKaBPJS.getText().isBlank()) {
            if (!ceksukses) {
                ceksukses = true;
                this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                tbKamar.clearSelection();
                Valid.tabelKosongSmc(tabMode);
                final String tglawal = Valid.getTglSmc(TanggalAwal);
                final String tglakhir = Valid.getTglSmc(TanggalAkhir);
                final String nopeserta = NoKaBPJS.getText().trim();
                new SwingWorker<String, Object[]>() {
                    final ObjectMapper mapper = new ObjectMapper();
                    String namapeserta = "";
                    String tgllahir = "";

                    @Override
                    protected String doInBackground() throws Exception {
                        try {
                            HttpHeaders headers = new HttpHeaders();
                            String utc = api.getUTCDateTime();
                            headers.setContentType(MediaType.APPLICATION_JSON);
                            headers.add("x-cons-id", koneksiDB.CONSIDAPIAPOTEKBPJS());
                            headers.add("x-timestamp", utc);
                            headers.add("x-signature", api.getHmac(utc));
                            headers.add("user_key", koneksiDB.USERKEYAPIAPOTEKBPJS());
                            String url = new StringJoiner("/").add(koneksiDB.URLAPIAPOTEKBPJS()).add("riwayatobat").add(tglawal).add(tglakhir).add(nopeserta).toString();
                            System.out.println(url);
                            JsonNode root = mapper.readTree(api.getRest().exchange(url, HttpMethod.GET, new HttpEntity(headers), String.class).getBody());
                            System.out.println(root.toString());
                            JsonNode metadata = root.path("metaData");
                            if (metadata.path("code").asText().equals("200")) {
                                ObjectNode response = mapper.readTree(api.Decrypt(root.path("response").asText(), utc)).withObject("list");
                                namapeserta = response.path("namapeserta").asText("");
                                tgllahir = response.path("tgllhr").asText("");

                                response.withArray("history").forEach(node -> publish(new Object[] {
                                    node.path("nosjp").asText(),
                                    node.path("tglpelayanan").asText(),
                                    node.path("noresep").asText(),
                                    node.path("kodeobat").asText(),
                                    node.path("namaobat").asText(),
                                    node.path("jmlobat").asDouble()
                                }));
                            } else {
                                namapeserta = "";
                                tgllahir = "";
                                return metadata.path("message").asText();
                            }
                        } catch (HttpClientErrorException | HttpServerErrorException e) {
                            System.out.println(e.getResponseBodyAsString());
                            throw e;
                        }
                        return null;
                    }

                    @Override
                    protected void process(List<Object[]> chunks) {
                        chunks.forEach(tabMode::addRow);
                    }

                    @Override
                    protected void done() {
                        try {
                            String message = get();
                            namaPasien.setText(namapeserta);
                            tglLahir.setText(tgllahir);
                            if (message != null) {
                                JOptionPane.showMessageDialog(null, message, "Peringatan", JOptionPane.WARNING_MESSAGE);
                            }
                        } catch (Exception e) {
                            System.out.println("Notif : " + e);
                            if (e.toString().contains("UnknownHostException")) {
                                JOptionPane.showMessageDialog(null, "Koneksi ke server BPJS terputus..!!", "Peringatan", JOptionPane.WARNING_MESSAGE);
                            }
                        }
                        tabMode.fireTableDataChanged();
                        LCount.setText(tabMode.getRowCount() + "");
                        ApotekBPJSRiwayatPelayananObatSMC.this.setCursor(Cursor.getDefaultCursor());
                        ceksukses = false;
                    }
                }.execute();
            }
        }
    }
}
