/*
  Dilarang keras menggandakan/mengcopy/menyebarkan/membajak/mendecompile
  Software ini dalam bentuk apapun tanpa seijin pembuat software
  (Khanza.Soft Media). Bagi yang sengaja membajak softaware ini ta
  npa ijin, kami sumpahi sial 1000 turunan, miskin sampai 500 turu
  nan. Selalu mendapat kecelakaan sampai 400 turunan. Anak pertama
  nya cacat tidak punya kaki sampai 300 turunan. Susah cari jodoh
  sampai umur 50 tahun sampai 200 turunan. Ya Alloh maafkan kami
  karena telah berdoa buruk, semua ini kami lakukan karena kami ti
  dak pernah rela karya kami dibajak tanpa ijin.
 */
package bridging;

import fungsi.WarnaTable;
import java.awt.Dimension;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import fungsi.akses;
import fungsi.validasi;
import fungsi.koneksiDB;
import fungsi.sekuel;
import java.awt.Cursor;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.time.LocalDate;
import java.time.YearMonth;
import java.util.List;
import java.util.stream.StreamSupport;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;
import simrskhanza.DlgPasien;

/**
 *
 * @author dosen
 */
public final class BPJSCekRiwayatSuratKontrolSMC extends javax.swing.JDialog {
    private final DefaultTableModel tabMode;
    private final validasi Valid = new validasi();
    private final sekuel Sequel = new sekuel();
    private final ApiBPJS api = new ApiBPJS();
    private DlgPasien pasien = null;
    private volatile boolean isLoading = false;
    private int i = 0;
    private String URL = "", link = "";

    /**
     * Creates new form DlgKamar
     *
     * @param parent
     * @param modal
     */
    public BPJSCekRiwayatSuratKontrolSMC(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.setLocation(10, 2);
        setSize(628, 674);

        tabMode = new DefaultTableModel(null, new Object[] {
            "No. Surat", "No. Kartu", "Nama Pasien", "Jenis Pelayanan", "Jenis Kontrol", "Tgl. Entri",
            "Tgl. Rencana", "No. SEP Asal", "Tgl. SEP", "kdpoli", "Poli Asal", "kdpolitujuan", "Poli Tujuan",
            "kddpjp", "Dokter DPJP", "Sudah Terbit SEP"
        }) {
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        tbKamar.setModel(tabMode);

        //tbKamar.setDefaultRenderer(Object.class, new WarnaTable(panelJudul.getBackground(),tbKamar.getBackground()));
        tbKamar.setPreferredScrollableViewportSize(new Dimension(500, 500));
        tbKamar.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        for (i = 0; i < tabMode.getColumnCount(); i++) {
            TableColumn column = tbKamar.getColumnModel().getColumn(i);
            if (i == 0) {
                column.setPreferredWidth(120);
            } else if (i == 1) {
                column.setPreferredWidth(90);
            } else if (i == 2) {
                column.setPreferredWidth(210);
            } else if (i == 3) {
                column.setPreferredWidth(90);
            } else if (i == 4) {
                column.setPreferredWidth(160);
            } else if (i == 5) {
                column.setPreferredWidth(85);
            } else if (i == 6) {
                column.setPreferredWidth(85);
            } else if (i == 7) {
                column.setPreferredWidth(160);
            } else if (i == 9) {
                column.setMinWidth(0);
                column.setMaxWidth(0);
            } else if (i == 10) {
                column.setPreferredWidth(100);
            } else if (i == 11) {
                column.setMinWidth(0);
                column.setMaxWidth(0);
            } else if (i == 12) {
                column.setPreferredWidth(120);
            } else if (i == 13) {
                column.setMinWidth(0);
                column.setMaxWidth(0);
            } else if (i == 14) {
                column.setPreferredWidth(190);
            } else if (i == 15) {
                column.setPreferredWidth(100);
            }
        }

        tbKamar.setDefaultRenderer(Object.class, new WarnaTable());
        try {
            link = koneksiDB.URLAPIBPJS();
        } catch (Exception e) {
            System.out.println("E : " + e);
        }

        Valid.LoadTahun(ThnCari);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        ppTarikDataSKDP = new javax.swing.JMenuItem();
        internalFrame1 = new widget.InternalFrame();
        Scroll = new widget.ScrollPane();
        tbKamar = new widget.Table();
        panelGlass6 = new widget.panelisi();
        jLabel18 = new widget.Label();
        JenisTgl = new widget.ComboBox();
        label11 = new widget.Label();
        ThnCari = new widget.ComboBox();
        BlnCari = new widget.ComboBox();
        jLabel16 = new widget.Label();
        NoKartu = new widget.TextBox();
        btnPasien = new widget.Button();
        BtnCari = new widget.Button();
        jLabel17 = new widget.Label();
        BtnKeluar = new widget.Button();

        jPopupMenu1.setForeground(new java.awt.Color(50, 50, 50));
        jPopupMenu1.setName("jPopupMenu1"); // NOI18N

        ppTarikDataSKDP.setBackground(new java.awt.Color(255, 255, 254));
        ppTarikDataSKDP.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        ppTarikDataSKDP.setForeground(new java.awt.Color(50, 50, 50));
        ppTarikDataSKDP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/category.png"))); // NOI18N
        ppTarikDataSKDP.setText("Tarik data SKDP");
        ppTarikDataSKDP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ppTarikDataSKDP.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ppTarikDataSKDP.setName("ppTarikDataSKDP"); // NOI18N
        ppTarikDataSKDP.setPreferredSize(new java.awt.Dimension(200, 26));
        ppTarikDataSKDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppTarikDataSKDPActionPerformed(evt);
            }
        });
        jPopupMenu1.add(ppTarikDataSKDP);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(null);
        setIconImages(null);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Pencarian Riwayat Surat Kontrol VClaim ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        Scroll.setName("Scroll"); // NOI18N
        Scroll.setOpaque(true);

        tbKamar.setAutoCreateRowSorter(true);
        tbKamar.setToolTipText("Silahkan klik untuk memilih data yang mau diedit ataupun dihapus");
        tbKamar.setComponentPopupMenu(jPopupMenu1);
        tbKamar.setName("tbKamar"); // NOI18N
        Scroll.setViewportView(tbKamar);

        internalFrame1.add(Scroll, java.awt.BorderLayout.CENTER);

        panelGlass6.setName("panelGlass6"); // NOI18N
        panelGlass6.setPreferredSize(new java.awt.Dimension(44, 54));
        panelGlass6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        jLabel18.setText("Tanggal");
        jLabel18.setName("jLabel18"); // NOI18N
        jLabel18.setPreferredSize(new java.awt.Dimension(40, 23));
        panelGlass6.add(jLabel18);

        JenisTgl.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Entri", "Rencana Kontrol" }));
        JenisTgl.setSelectedIndex(1);
        JenisTgl.setName("JenisTgl"); // NOI18N
        JenisTgl.setPreferredSize(new java.awt.Dimension(120, 23));
        panelGlass6.add(JenisTgl);

        label11.setText(":");
        label11.setName("label11"); // NOI18N
        label11.setPreferredSize(new java.awt.Dimension(15, 23));
        panelGlass6.add(label11);

        ThnCari.setName("ThnCari"); // NOI18N
        ThnCari.setPreferredSize(new java.awt.Dimension(80, 23));
        panelGlass6.add(ThnCari);

        BlnCari.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        BlnCari.setName("BlnCari"); // NOI18N
        BlnCari.setPreferredSize(new java.awt.Dimension(62, 23));
        panelGlass6.add(BlnCari);

        jLabel16.setText("No.Kartu :");
        jLabel16.setName("jLabel16"); // NOI18N
        jLabel16.setPreferredSize(new java.awt.Dimension(55, 23));
        panelGlass6.add(jLabel16);

        NoKartu.setName("NoKartu"); // NOI18N
        NoKartu.setPreferredSize(new java.awt.Dimension(130, 23));
        panelGlass6.add(NoKartu);

        btnPasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/190.png"))); // NOI18N
        btnPasien.setMnemonic('5');
        btnPasien.setToolTipText("Alt+5");
        btnPasien.setName("btnPasien"); // NOI18N
        btnPasien.setPreferredSize(new java.awt.Dimension(28, 23));
        btnPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasienActionPerformed(evt);
            }
        });
        btnPasien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPasienKeyPressed(evt);
            }
        });
        panelGlass6.add(btnPasien);

        BtnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        BtnCari.setMnemonic('6');
        BtnCari.setToolTipText("Alt+6");
        BtnCari.setName("BtnCari"); // NOI18N
        BtnCari.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariActionPerformed(evt);
            }
        });
        BtnCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnCariKeyPressed(evt);
            }
        });
        panelGlass6.add(BtnCari);

        jLabel17.setName("jLabel17"); // NOI18N
        jLabel17.setPreferredSize(new java.awt.Dimension(30, 23));
        panelGlass6.add(jLabel17);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelGlass6.add(BtnKeluar);

        internalFrame1.add(panelGlass6, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            dispose();
        }
    }//GEN-LAST:event_BtnKeluarKeyPressed

    private void BtnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariActionPerformed
        tampilSmc();
    }//GEN-LAST:event_BtnCariActionPerformed

    private void BtnCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnCariKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            BtnCariActionPerformed(null);
        } else {
            Valid.pindah(evt, NoKartu, BtnKeluar);
        }
    }//GEN-LAST:event_BtnCariKeyPressed

    private void ppTarikDataSKDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppTarikDataSKDPActionPerformed
        if (tbKamar.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(null, "Silahkan pilih data rencana kontrol yang mau ditarik..!!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else {
            if (tbKamar.getValueAt(tbKamar.getSelectedRow(), 4).toString().startsWith("1")) {
                JOptionPane.showMessageDialog(null, "Maaf, hanya bisa menarik data rencana kontrol..!!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            } else {
                if (!Sequel.menyimpantfSmc("bridging_surat_kontrol_bpjs", null, (String) tbKamar.getValueAt(tbKamar.getSelectedRow(), 7),
                    (String) tbKamar.getValueAt(tbKamar.getSelectedRow(), 5), (String) tbKamar.getValueAt(tbKamar.getSelectedRow(), 0),
                    (String) tbKamar.getValueAt(tbKamar.getSelectedRow(), 6), (String) tbKamar.getValueAt(tbKamar.getSelectedRow(), 13),
                    (String) tbKamar.getValueAt(tbKamar.getSelectedRow(), 14), (String) tbKamar.getValueAt(tbKamar.getSelectedRow(), 11),
                    (String) tbKamar.getValueAt(tbKamar.getSelectedRow(), 12), "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
                    "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""
                )) {
                    JOptionPane.showMessageDialog(null, "Gagal menyimpan data rencana kontrol..!!", "Gagal", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_ppTarikDataSKDPActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        isCek();
    }//GEN-LAST:event_formWindowActivated

    private void btnPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasienActionPerformed
        resolveDlgPasien();
        pasien.setVisible(true);
    }//GEN-LAST:event_btnPasienActionPerformed

    private void btnPasienKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnPasienKeyPressed
        Valid.pindah(evt, NoKartu, BtnKeluar);
    }//GEN-LAST:event_btnPasienKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            BPJSCekRiwayatSuratKontrolSMC dialog = new BPJSCekRiwayatSuratKontrolSMC(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.ComboBox BlnCari;
    private widget.Button BtnCari;
    private widget.Button BtnKeluar;
    private widget.ComboBox JenisTgl;
    private widget.TextBox NoKartu;
    private widget.ScrollPane Scroll;
    private widget.ComboBox ThnCari;
    private widget.Button btnPasien;
    private widget.InternalFrame internalFrame1;
    private widget.Label jLabel16;
    private widget.Label jLabel17;
    private widget.Label jLabel18;
    private javax.swing.JPopupMenu jPopupMenu1;
    private widget.Label label11;
    private widget.panelisi panelGlass6;
    private javax.swing.JMenuItem ppTarikDataSKDP;
    private widget.Table tbKamar;
    // End of variables declaration//GEN-END:variables

    public void setPasien(String noKartu) {
        NoKartu.setText(noKartu);
        LocalDate d = LocalDate.now();
        ThnCari.setSelectedItem(d.getYear());
        BlnCari.setSelectedIndex(d.getMonthValue() - 1);
    }

    private void tampilSmc() {
        if (!isLoading) {
            isLoading = true;
            Valid.tabelKosongSmc(tabMode);
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            final String nokartu = NoKartu.getText();
            final String tahun = ThnCari.getSelectedItem().toString();
            final String bulan = BlnCari.getSelectedItem().toString();
            final YearMonth ym = YearMonth.of(Integer.parseInt(tahun), Integer.parseInt(bulan));
            final String jenis = String.valueOf(JenisTgl.getSelectedIndex() + 1);

            new SwingWorker<Void, Object[]>() {
                @Override
                protected Void doInBackground() throws Exception {
                    String utc = api.getCurrentTimestampAsString();
                    HttpHeaders headers = new HttpHeaders();
                    headers.setContentType(MediaType.APPLICATION_JSON);
                    headers.add("X-Cons-ID", koneksiDB.CONSIDAPIBPJS());
                    headers.add("X-Timestamp", utc);
                    headers.add("X-Signature", api.getHmac(utc));
                    headers.add("user_key", koneksiDB.USERKEYAPIBPJS());
                    if (nokartu.isBlank()) {
                        URL = link + "RencanaKontrol/ListRencanaKontrol/tglAwal/" + ym.atDay(1).toString() + "/tglAkhir/" + ym.atEndOfMonth().toString() + "/filter/" + jenis;
                    } else {
                        URL = link + "/RencanaKontrol/ListRencanaKontrol/Bulan/" + bulan + "/Tahun/" + tahun + "/Nokartu/" + nokartu + "/filter/" + jenis;
                    }
                    System.out.println("URL : " + URL);
                    final ObjectMapper mapper = new ObjectMapper();
                    JsonNode root = mapper.readTree(api.getRest().exchange(URL, HttpMethod.GET, new HttpEntity(headers), String.class).getBody());
                    JsonNode metadata = root.path("metaData");
                    if (metadata.path("code").asText().equals("200")) {
                        JsonNode response = mapper.readTree(api.Decrypt(root.path("response").asText(), utc)).path("list");
                        if (response.isArray()) {
                            StreamSupport.stream(response.spliterator(), false)
                                .forEach(node -> publish(new Object[] {
                                    node.path("noSuratKontrol").asText(""), node.path("noKartu").asText(""), node.path("nama").asText(""), node.path("jnsPelayanan").asText(""),
                                    node.path("jnsKontrol").asText("") + ". " + node.path("namaJnsKontrol").asText(""), node.path("tglTerbitKontrol").asText(""),
                                    node.path("tglRencanaKontrol").asText(""), node.path("noSepAsalKontrol").asText(""), node.path("tglSEP").asText(""),
                                    node.path("poliAsal").asText(""), node.path("namaPoliAsal").asText(""), node.path("poliTujuan").asText(""),
                                    node.path("namaPoliTujuan").asText(""), node.path("kodeDokter").asText(""), node.path("namaDokter").asText(""),
                                    node.path("terbitSEP").asText("")
                                }));
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, metadata.path("message").asText(""), "Peringatan", JOptionPane.WARNING_MESSAGE);
                    }

                    return null;
                }

                @Override
                protected void process(List<Object[]> chunks) {
                    chunks.forEach(tabMode::addRow);
                }

                @Override
                protected void done() {
                    try {
                        get();
                    } catch (Exception e) {
                        System.out.println("Notif : " + e);
                    }
                    isLoading = false;
                    tabMode.fireTableDataChanged();
                    BPJSCekRiwayatSuratKontrolSMC.this.setCursor(Cursor.getDefaultCursor());
                }
            }.execute();
        }
    }

    private void isCek() {
        ppTarikDataSKDP.setEnabled(akses.getbpjs_surat_kontrol());
    }

    private void resolveDlgPasien() {
        if (pasien == null) {
            pasien = new DlgPasien(null, false);
            pasien.emptTeks();
            pasien.isCek();
            pasien.setSize(internalFrame1.getWidth() - 20, internalFrame1.getHeight() - 20);
            pasien.setLocationRelativeTo(internalFrame1);
            pasien.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent e) {
                    if (pasien.getTable().getSelectedRow() != -1) {
                        if (pasien.getTable().getValueAt(pasien.getTable().getSelectedRow(), 20).toString().equals("")) {
                            JOptionPane.showMessageDialog(rootPane, "Maaf pasien tidak punya Nomor Kartu...!");
                        } else {
                            NoKartu.setText(pasien.getTable().getValueAt(pasien.getTable().getSelectedRow(), 20).toString());
                        }
                    }
                    if (pasien.getTable2().getSelectedRow() != -1) {
                        if (pasien.getTable2().getValueAt(pasien.getTable2().getSelectedRow(), 20).toString().equals("")) {
                            JOptionPane.showMessageDialog(rootPane, "Maaf pasien tidak punya Nomor Kartu...!");
                        } else {
                            NoKartu.setText(pasien.getTable2().getValueAt(pasien.getTable2().getSelectedRow(), 20).toString());
                        }
                    }
                    if (pasien.getTable3().getSelectedRow() != -1) {
                        if (pasien.getTable3().getValueAt(pasien.getTable3().getSelectedRow(), 20).toString().equals("")) {
                            JOptionPane.showMessageDialog(rootPane, "Maaf pasien tidak punya Nomor Kartu...!");
                        } else {
                            NoKartu.setText(pasien.getTable3().getValueAt(pasien.getTable3().getSelectedRow(), 20).toString());
                        }
                    }
                }
            });

            pasien.getTable().addKeyListener(new KeyAdapter() {
                @Override
                public void keyPressed(KeyEvent e) {
                    if (e.getKeyCode() == KeyEvent.VK_SPACE) {
                        pasien.dispose();
                    }
                }
            });

            pasien.getTable2().addKeyListener(new KeyAdapter() {
                @Override
                public void keyPressed(KeyEvent e) {
                    if (e.getKeyCode() == KeyEvent.VK_SPACE) {
                        pasien.dispose();
                    }
                }
            });

            pasien.getTable3().addKeyListener(new KeyAdapter() {
                @Override
                public void keyPressed(KeyEvent e) {
                    if (e.getKeyCode() == KeyEvent.VK_SPACE) {
                        pasien.dispose();
                    }
                }
            });
        }
    }
}
