/*
  Kontribusi dari Mas Abdul Wahid RSUD Cipayung & Mas Fanji dari RSUD Kramatjati

 */
package bridging;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import fungsi.WarnaTable;
import fungsi.batasInput;
import fungsi.koneksiDB;
import fungsi.validasi;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.security.KeyManagementException;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.security.cert.CertificateException;
import java.security.cert.X509Certificate;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import javax.net.ssl.SSLContext;
import javax.net.ssl.TrustManager;
import javax.net.ssl.X509TrustManager;
import javax.swing.JTable;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import org.apache.http.client.utils.URIBuilder;
import org.apache.http.conn.scheme.Scheme;
import org.apache.http.conn.ssl.SSLSocketFactory;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;
import org.springframework.http.client.HttpComponentsClientHttpRequestFactory;
import org.springframework.web.client.RestTemplate;

/**
 *
 * @author dosen
 */
public final class DlgPencarianSnomedSMC extends javax.swing.JDialog {
    private final DefaultTableModel tabMode;
    private final DefaultTableModel tabModeDetail;
    private final validasi Valid = new validasi();
    private final String URLAPISNOWSTORMSMC = koneksiDB.URLAPISNOWSTORMSMC();
    private volatile boolean ceksukses = false;
    private boolean fetchNext = true;
    private String lastFilter = "";
    private String lastParameter = "";

    /**
     * Creates new form DlgKamar
     *
     * @param parent
     * @param modal
     */
    public DlgPencarianSnomedSMC(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        tabMode = new DefaultTableModel(null, new String[] {"Code", "System", "Display"}) {
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };

        tbKamar.setModel(tabMode);
        tbKamar.setPreferredScrollableViewportSize(new Dimension(500, 500));
        tbKamar.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        for (int i = 0; i < tabMode.getColumnCount(); i++) {
            TableColumn column = tbKamar.getColumnModel().getColumn(i);
            if (i == 0) {
                column.setPreferredWidth(70);
            } else if (i == 1) {
                column.setPreferredWidth(130);
            } else if (i == 2) {
                column.setPreferredWidth(500);
            }
        }
        tbKamar.setDefaultRenderer(Object.class, new WarnaTable());

        tabModeDetail = new DefaultTableModel(null, new String[] {"Key", "Value"}) {
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };

        tbKamar1.setModel(tabModeDetail);
        tbKamar1.setPreferredScrollableViewportSize(new Dimension(500, 500));
        tbKamar1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        for (int i = 0; i < tabModeDetail.getColumnCount(); i++) {
            TableColumn column = tbKamar1.getColumnModel().getColumn(i);
            if (i == 0) {
                column.setPreferredWidth(250);
            } else if (i == 1) {
                column.setPreferredWidth(600);
            }
        }
        tbKamar1.setDefaultRenderer(Object.class, new WarnaTable());

        TCari.setDocument(new batasInput((byte) 100).getKata(TCari));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Popup = new javax.swing.JPopupMenu();
        MnDetailKode = new javax.swing.JMenuItem();
        ppCariTurunan = new javax.swing.JMenuItem();
        ppCariMemberRefset = new javax.swing.JMenuItem();
        WindowDetailKode = new javax.swing.JDialog();
        internalFrame2 = new widget.InternalFrame();
        Scroll1 = new widget.ScrollPane();
        tbKamar1 = new widget.Table();
        panelGlass7 = new widget.panelisi();
        BtnLihatTurunan = new widget.Button();
        BtnKeluar1 = new widget.Button();
        internalFrame1 = new widget.InternalFrame();
        Scroll = new widget.ScrollPane();
        tbKamar = new widget.Table();
        panelGlass6 = new widget.panelisi();
        jLabel6 = new widget.Label();
        LimitData = new widget.ComboBox();
        jLabel17 = new widget.Label();
        TParameter = new widget.TextBox();
        jLabel16 = new widget.Label();
        TCari = new widget.TextBox();
        BtnCari = new widget.Button();
        BtnAll = new widget.Button();
        jLabel8 = new widget.Label();
        LCount = new widget.Label();
        BtnKeluar = new widget.Button();

        Popup.setName("Popup"); // NOI18N

        MnDetailKode.setBackground(new java.awt.Color(255, 255, 254));
        MnDetailKode.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        MnDetailKode.setForeground(new java.awt.Color(50, 50, 50));
        MnDetailKode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/category.png"))); // NOI18N
        MnDetailKode.setText("Detail Kode");
        MnDetailKode.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MnDetailKode.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        MnDetailKode.setName("MnDetailKode"); // NOI18N
        MnDetailKode.setPreferredSize(new java.awt.Dimension(168, 30));
        MnDetailKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnDetailKodeActionPerformed(evt);
            }
        });
        Popup.add(MnDetailKode);

        ppCariTurunan.setBackground(new java.awt.Color(255, 255, 254));
        ppCariTurunan.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        ppCariTurunan.setForeground(new java.awt.Color(50, 50, 50));
        ppCariTurunan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/category.png"))); // NOI18N
        ppCariTurunan.setText("Cari Daftar Turunan dari Kode Ini");
        ppCariTurunan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ppCariTurunan.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ppCariTurunan.setName("ppCariTurunan"); // NOI18N
        ppCariTurunan.setPreferredSize(new java.awt.Dimension(147, 30));
        ppCariTurunan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppCariTurunanActionPerformed(evt);
            }
        });
        Popup.add(ppCariTurunan);
        ppCariTurunan.getAccessibleContext().setAccessibleName("Cari Berdasarkan Kode Turunan");

        ppCariMemberRefset.setBackground(new java.awt.Color(255, 255, 254));
        ppCariMemberRefset.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        ppCariMemberRefset.setForeground(new java.awt.Color(50, 50, 50));
        ppCariMemberRefset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/category.png"))); // NOI18N
        ppCariMemberRefset.setText("Cari Daftar Member Refset dari Kode Ini");
        ppCariMemberRefset.setToolTipText("");
        ppCariMemberRefset.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ppCariMemberRefset.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ppCariMemberRefset.setName("ppCariMemberRefset"); // NOI18N
        ppCariMemberRefset.setPreferredSize(new java.awt.Dimension(216, 30));
        ppCariMemberRefset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppCariMemberRefsetActionPerformed(evt);
            }
        });
        Popup.add(ppCariMemberRefset);
        ppCariMemberRefset.getAccessibleContext().setAccessibleName("Cari Berdasarkan Member Refset");

        WindowDetailKode.setAlwaysOnTop(true);
        WindowDetailKode.setName("WindowDetailKode"); // NOI18N
        WindowDetailKode.setUndecorated(true);
        WindowDetailKode.setResizable(false);

        internalFrame2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Detail Kode Snomed ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame2.setName("internalFrame2"); // NOI18N
        internalFrame2.setLayout(new java.awt.BorderLayout());

        Scroll1.setName("Scroll1"); // NOI18N
        Scroll1.setOpaque(true);

        tbKamar1.setName("tbKamar1"); // NOI18N
        Scroll1.setViewportView(tbKamar1);

        internalFrame2.add(Scroll1, java.awt.BorderLayout.CENTER);

        panelGlass7.setName("panelGlass7"); // NOI18N
        panelGlass7.setPreferredSize(new java.awt.Dimension(44, 54));
        panelGlass7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        BtnLihatTurunan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Search-16x16.png"))); // NOI18N
        BtnLihatTurunan.setMnemonic('K');
        BtnLihatTurunan.setText("Lihat Turunan");
        BtnLihatTurunan.setToolTipText("Alt+K");
        BtnLihatTurunan.setEnabled(false);
        BtnLihatTurunan.setName("BtnLihatTurunan"); // NOI18N
        BtnLihatTurunan.setPreferredSize(new java.awt.Dimension(130, 30));
        BtnLihatTurunan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLihatTurunanActionPerformed(evt);
            }
        });
        panelGlass7.add(BtnLihatTurunan);

        BtnKeluar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar1.setMnemonic('K');
        BtnKeluar1.setText("Keluar");
        BtnKeluar1.setToolTipText("Alt+K");
        BtnKeluar1.setName("BtnKeluar1"); // NOI18N
        BtnKeluar1.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluar1ActionPerformed(evt);
            }
        });
        panelGlass7.add(BtnKeluar1);

        internalFrame2.add(panelGlass7, java.awt.BorderLayout.PAGE_END);

        WindowDetailKode.getContentPane().add(internalFrame2, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(null);
        setIconImages(null);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Pencarian Referensi Snomed CT via API ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout());

        Scroll.setName("Scroll"); // NOI18N
        Scroll.setOpaque(true);

        tbKamar.setComponentPopupMenu(Popup);
        tbKamar.setName("tbKamar"); // NOI18N
        tbKamar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbKamarMousePressed(evt);
            }
        });
        Scroll.setViewportView(tbKamar);

        internalFrame1.add(Scroll, java.awt.BorderLayout.CENTER);

        panelGlass6.setName("panelGlass6"); // NOI18N
        panelGlass6.setPreferredSize(new java.awt.Dimension(44, 54));
        panelGlass6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        jLabel6.setText("Limit Data :");
        jLabel6.setName("jLabel6"); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(70, 23));
        panelGlass6.add(jLabel6);

        LimitData.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "50", "100", "200", "300" }));
        LimitData.setName("LimitData"); // NOI18N
        LimitData.setPreferredSize(new java.awt.Dimension(70, 23));
        panelGlass6.add(LimitData);

        jLabel17.setText("Query :");
        jLabel17.setName("jLabel17"); // NOI18N
        jLabel17.setPreferredSize(new java.awt.Dimension(50, 23));
        panelGlass6.add(jLabel17);

        TParameter.setName("TParameter"); // NOI18N
        TParameter.setPreferredSize(new java.awt.Dimension(250, 23));
        TParameter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TParameterKeyPressed(evt);
            }
        });
        panelGlass6.add(TParameter);

        jLabel16.setText("Filter :");
        jLabel16.setName("jLabel16"); // NOI18N
        jLabel16.setPreferredSize(new java.awt.Dimension(50, 23));
        panelGlass6.add(jLabel16);

        TCari.setName("TCari"); // NOI18N
        TCari.setPreferredSize(new java.awt.Dimension(150, 23));
        TCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TCariKeyPressed(evt);
            }
        });
        panelGlass6.add(TCari);

        BtnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        BtnCari.setMnemonic('6');
        BtnCari.setToolTipText("Alt+6");
        BtnCari.setName("BtnCari"); // NOI18N
        BtnCari.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariActionPerformed(evt);
            }
        });
        BtnCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnCariKeyPressed(evt);
            }
        });
        panelGlass6.add(BtnCari);

        BtnAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Search-16x16.png"))); // NOI18N
        BtnAll.setMnemonic('2');
        BtnAll.setToolTipText("2Alt+2");
        BtnAll.setName("BtnAll"); // NOI18N
        BtnAll.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAllActionPerformed(evt);
            }
        });
        BtnAll.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnAllKeyPressed(evt);
            }
        });
        panelGlass6.add(BtnAll);

        jLabel8.setText("Record :");
        jLabel8.setName("jLabel8"); // NOI18N
        jLabel8.setPreferredSize(new java.awt.Dimension(60, 23));
        panelGlass6.add(jLabel8);

        LCount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LCount.setText("0 / 0");
        LCount.setName("LCount"); // NOI18N
        LCount.setPreferredSize(new java.awt.Dimension(70, 23));
        panelGlass6.add(LCount);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelGlass6.add(BtnKeluar);

        internalFrame1.add(panelGlass6, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            dispose();
        }
    }//GEN-LAST:event_BtnKeluarKeyPressed

    private void TCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCariKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            BtnCariActionPerformed(null);
        } else {
            Valid.pindahSmc(evt, tbKamar, BtnAll);
        }
    }//GEN-LAST:event_TCariKeyPressed

    private void BtnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariActionPerformed
        tampilSmc();
    }//GEN-LAST:event_BtnCariActionPerformed

    private void BtnCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnCariKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            BtnCariActionPerformed(null);
        }
    }//GEN-LAST:event_BtnCariKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        TCari.requestFocus();
    }//GEN-LAST:event_formWindowActivated

    private void BtnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAllActionPerformed
        TCari.setText("");
        tampilSmc();
    }//GEN-LAST:event_BtnAllActionPerformed

    private void BtnAllKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnAllKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            BtnAllActionPerformed(null);
        }
    }//GEN-LAST:event_BtnAllKeyPressed

    private void ppCariTurunanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppCariTurunanActionPerformed
        TParameter.setText("ecl/<<" + tbKamar.getValueAt(tbKamar.getSelectedRow(), 0).toString() + " |" + tbKamar.getValueAt(tbKamar.getSelectedRow(), 2).toString() + "|");
        TCari.setText("");
        tampilSmc();
    }//GEN-LAST:event_ppCariTurunanActionPerformed

    private void ppCariMemberRefsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppCariMemberRefsetActionPerformed
        TParameter.setText("refset/" + tbKamar.getValueAt(tbKamar.getSelectedRow(), 0).toString());
        TCari.setText("");
        tampilSmc();
    }//GEN-LAST:event_ppCariMemberRefsetActionPerformed

    private void MnDetailKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnDetailKodeActionPerformed
        WindowDetailKode.setSize(internalFrame1.getWidth() - 20, internalFrame1.getHeight() - 20);
        WindowDetailKode.setLocationRelativeTo(internalFrame1);
        WindowDetailKode.setVisible(true);
        tampilLookupSmc();
    }//GEN-LAST:event_MnDetailKodeActionPerformed

    private void TParameterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TParameterKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            BtnCariActionPerformed(null);
        }
    }//GEN-LAST:event_TParameterKeyPressed

    private void tbKamarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKamarMousePressed
        int row = tbKamar.rowAtPoint(evt.getPoint());
        int column = tbKamar.columnAtPoint(evt.getPoint());
        tbKamar.changeSelection(row, column, false, false);
    }//GEN-LAST:event_tbKamarMousePressed

    private void BtnKeluar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluar1ActionPerformed
        Valid.tabelKosong(tabModeDetail);
        WindowDetailKode.setVisible(false);
    }//GEN-LAST:event_BtnKeluar1ActionPerformed

    private void BtnLihatTurunanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLihatTurunanActionPerformed
        TParameter.setText("ecl/<!" + tbKamar.getValueAt(tbKamar.getSelectedRow(), 0).toString() + " |" + tbKamar.getValueAt(tbKamar.getSelectedRow(), 2).toString() + "|");
        TCari.setText("");
        tampilSmc();
        Valid.tabelKosong(tabModeDetail);
        WindowDetailKode.setVisible(false);
    }//GEN-LAST:event_BtnLihatTurunanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgPencarianSnomedSMC dialog = new DlgPencarianSnomedSMC(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnAll;
    private widget.Button BtnCari;
    private widget.Button BtnKeluar;
    private widget.Button BtnKeluar1;
    private widget.Button BtnLihatTurunan;
    private widget.Label LCount;
    private widget.ComboBox LimitData;
    private javax.swing.JMenuItem MnDetailKode;
    private javax.swing.JPopupMenu Popup;
    private widget.ScrollPane Scroll;
    private widget.ScrollPane Scroll1;
    private widget.TextBox TCari;
    private widget.TextBox TParameter;
    private javax.swing.JDialog WindowDetailKode;
    private widget.InternalFrame internalFrame1;
    private widget.InternalFrame internalFrame2;
    private widget.Label jLabel16;
    private widget.Label jLabel17;
    private widget.Label jLabel6;
    private widget.Label jLabel8;
    private widget.panelisi panelGlass6;
    private widget.panelisi panelGlass7;
    private javax.swing.JMenuItem ppCariMemberRefset;
    private javax.swing.JMenuItem ppCariTurunan;
    private widget.Table tbKamar;
    private widget.Table tbKamar1;
    // End of variables declaration//GEN-END:variables

    private void tampilSmc() {
        if (!ceksukses) {
            ceksukses = true;
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));

            final String pageRow = LimitData.getSelectedItem().toString();
            final String parameter = TParameter.getText().trim();
            final String filter = TCari.getText().trim();
            fetchNext = filter.equals(lastFilter) && parameter.equals(lastParameter);

            if (!fetchNext) {
                Valid.tabelKosongSmc(tabMode);
                LCount.setText("0 / 0");
            }

            final int offset = tabMode.getRowCount();

            new SwingWorker<Void, Object[]>() {
                private int totalRecords = 0;
                private final ObjectMapper mapper = new ObjectMapper();

                @Override
                protected Void doInBackground() throws Exception {
                    HttpHeaders headers = new HttpHeaders();
                    headers.setAccept(Collections.singletonList(MediaType.APPLICATION_JSON));

                    URIBuilder uri = new URIBuilder(URLAPISNOWSTORMSMC + "/ValueSet/$expand");
                    uri.addParameter("count", String.valueOf(pageRow));

                    if (!parameter.isBlank()) {
                        uri.addParameter("url", "http://snomed.info/sct?fhir_vs=" + parameter);
                    } else {
                        uri.addParameter("url", "http://snomed.info/sct?fhir_vs");
                    }

                    if (fetchNext) {
                        uri.addParameter("offset", String.valueOf(offset));
                    }

                    if (!filter.isBlank()) {
                        uri.addParameter("filter", filter);
                    }

                    System.out.println(uri.toString());
                    JsonNode root = mapper.readTree(http().exchange(uri.build(), HttpMethod.GET, new HttpEntity(headers), String.class).getBody());
                    totalRecords = root.path("expansion").path("total").asInt(0);
                    lastFilter = filter;
                    lastParameter = parameter;
                    System.out.println(root.toString());

                    root.path("expansion").withArray("contains").forEach(node -> publish(new Object[] {node.path("code").asText(""), node.path("system").asText(""), node.path("display").asText("")}));

                    return null;
                }

                @Override
                protected void process(List<Object[]> chunks) {
                    chunks.forEach(tabMode::addRow);
                }

                @Override
                protected void done() {
                    try {
                        get();
                    } catch (Exception e) {
                        System.out.println("Notif : " + e);
                    }
                    tabMode.fireTableDataChanged();
                    LCount.setText(tabMode.getRowCount() + " / " + totalRecords);
                    DlgPencarianSnomedSMC.this.setCursor(Cursor.getDefaultCursor());
                    ceksukses = false;
                }
            }.execute();
        }
    }

    private void tampilLookupSmc() {
        if (!ceksukses) {
            ceksukses = true;
            WindowDetailKode.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));

            final String code = tbKamar.getValueAt(tbKamar.getSelectedRow(), 0).toString();

            new SwingWorker<Void, Object[]>() {
                private final ObjectMapper mapper = new ObjectMapper();
                private boolean hasChildren = false;

                @Override
                protected Void doInBackground() throws Exception {
                    HttpHeaders headers = new HttpHeaders();
                    headers.setAccept(Collections.singletonList(MediaType.APPLICATION_JSON));

                    URIBuilder uri = new URIBuilder(URLAPISNOWSTORMSMC + "/CodeSystem/$lookup");
                    uri.addParameter("system", "http://snomed.info/sct");
                    uri.addParameter("code", code);
                    uri.addParameter("property", "*");

                    System.out.println(uri.toString());
                    JsonNode root = mapper.readTree(http().exchange(uri.build(), HttpMethod.GET, new HttpEntity<>(headers), String.class).getBody());

                    System.out.println(root.toString());

                    Map<String, String> simpleNames = Map.of(
                        "code", "Code",
                        "display", "Display",
                        "name", "System Name",
                        "system", "System URI",
                        "version", "Version"
                    );

                    for (JsonNode param : root.path("parameter")) {
                        String name = param.path("name").asText();
                        if (simpleNames.containsKey(name)) {
                            publish(new Object[] {
                                simpleNames.get(name),
                                param.path("value" + capitalize(name)).asText(param.path("valueString").asText(param.path("valueCode").asText(param.path("valueUri").asText(""))))
                            });
                        }
                    }

                    for (JsonNode param : root.path("parameter")) {
                        if (!"property".equals(param.path("name").asText())) {
                            continue;
                        }

                        String propCode = "";
                        String propValue = "";
                        for (JsonNode part : param.path("part")) {
                            String partName = part.path("name").asText();
                            if ("code".equals(partName)) {
                                propCode = part.path("valueCode").asText();
                            } else if ("value".equals(partName)) {
                                propValue = part.path("valueCode").asText(part.path("valueString").asText(part.path("valueBoolean").asText("")));
                            }
                        }

                        switch (propCode) {
                            case "parent":
                                publish(new Object[] {"Parent Code", propValue});
                                break;
                            case "moduleId":
                                publish(new Object[] {"Module ID", propValue});
                                break;
                            case "inactive":
                                publish(new Object[] {"Inactive", propValue});
                                break;
                            case "sufficientlyDefined":
                                publish(new Object[] {"Sufficiently Defined", propValue});
                                break;
                            case "effectiveTime":
                                publish(new Object[] {"Effective Time", propValue});
                                break;
                            case "normalForm":
                                publish(new Object[] {"Normal Form", propValue});
                                break;
                            case "normalFormTerse":
                                publish(new Object[] {"Normal Form (Terse)", propValue});
                                break;
                            case "child":
                                hasChildren = true;
                                break;
                        }
                    }

                    // Designations
                    for (JsonNode param : root.path("parameter")) {
                        if (!"designation".equals(param.path("name").asText())) {
                            continue;
                        }

                        String lang = "", use = "", value = "";
                        for (JsonNode part : param.path("part")) {
                            switch (part.path("name").asText()) {
                                case "language":
                                    lang = part.path("valueCode").asText();
                                    break;
                                case "use":
                                    use = part.path("valueCoding").path("display").asText(part.path("valueCoding").path("code").asText(""));
                                    break;
                                case "value":
                                    value = part.path("valueString").asText();
                                    break;
                            }
                        }
                        publish(new Object[] {"Designation [" + lang + "] " + use, value});
                    }

                    return null;
                }

                @Override
                protected void process(List<Object[]> chunks) {
                    chunks.forEach(tabModeDetail::addRow);
                    BtnLihatTurunan.setEnabled(hasChildren);
                }

                @Override
                protected void done() {
                    try {
                        get();
                    } catch (Exception e) {
                        System.out.println("Notif : " + e);
                    }
                    // tabModeDetail.fireTableDataChanged();
                    WindowDetailKode.setCursor(Cursor.getDefaultCursor());
                    ceksukses = false;
                }
            }.execute();
        }
    }

    private String capitalize(String s) {
        if (s == null || s.isEmpty()) {
            return s;
        }
        return Character.toUpperCase(s.charAt(0)) + s.substring(1);
    }

    public JTable getTable() {
        return tbKamar;
    }

    public void emptTeks() {
        TCari.setText("");
    }

    private RestTemplate http() throws NoSuchAlgorithmException, KeyManagementException {
        SSLContext sslContext = SSLContext.getInstance("SSL");
        TrustManager[] trustManagers = {
            new X509TrustManager() {
                @Override
                public X509Certificate[] getAcceptedIssuers() {
                    return null;
                }

                @Override
                public void checkServerTrusted(X509Certificate[] arg0, String arg1) throws CertificateException {
                }

                @Override
                public void checkClientTrusted(X509Certificate[] arg0, String arg1) throws CertificateException {
                }
            }
        };

        sslContext.init(null, trustManagers, new SecureRandom());
        SSLSocketFactory sslFactory = new SSLSocketFactory(sslContext, SSLSocketFactory.ALLOW_ALL_HOSTNAME_VERIFIER);
        Scheme scheme = new Scheme("https", 443, sslFactory);
        HttpComponentsClientHttpRequestFactory factory = new HttpComponentsClientHttpRequestFactory();

        factory.getHttpClient().getConnectionManager().getSchemeRegistry().register(scheme);
        return new RestTemplate(factory);
    }
}
