package kepegawaian;

import fungsi.WarnaTable;
import fungsi.akses;
import fungsi.batasInput;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingWorker;
import javax.swing.event.DocumentEvent;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.usermodel.WorkbookFactory;

/**
 *
 * @author dosen
 */
public class DlgJamMasukSMC extends javax.swing.JDialog {
    private static final int KOLOM_KODE = 1;
    private static final int KOLOM_NAMA = 2;
    private static final int KOLOM_JAM_MASUK = 8;
    private static final int KOLOM_JAM_PULANG = 11;
    private static final String TANPA_SHIFT = "-";

    private final DefaultTableModel tabMode;
    private final Connection koneksi = koneksiDB.condb();
    private final sekuel Sequel = new sekuel();
    private final validasi Valid = new validasi();
    private final ExecutorService executor = Executors.newSingleThreadExecutor();
    private volatile boolean ceksukses = false;
    private String kodeLama = "";

    /**
     * Creates new form DlgJadwal
     *
     * @param parent
     * @param modal
     */
    public DlgJamMasukSMC(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        tabMode = new DefaultTableModel(null, new Object[] {"P", "Kode", "Nama Shift", "Jam Masuk", "Jam Pulang", "Mapping Shift"}) {
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return colIndex == 0;
            }

            @Override
            public Class getColumnClass(int columnIndex) {
                if (columnIndex == 0) {
                    return Boolean.class;
                }
                return Object.class;
            }
        };
        tbJadwal.setModel(tabMode);
        tbJadwal.setPreferredScrollableViewportSize(new Dimension(500, 500));
        tbJadwal.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        for (int i = 0; i < tabMode.getColumnCount(); i++) {
            TableColumn column = tbJadwal.getColumnModel().getColumn(i);
            if (i == 0) {
                column.setPreferredWidth(20);
            } else if (i == 1) {
                column.setPreferredWidth(60);
            } else if (i == 2) {
                column.setPreferredWidth(230);
            } else {
                column.setPreferredWidth(120);
            }
        }
        tbJadwal.setDefaultRenderer(Object.class, new WarnaTable());
        TCari.setDocument(new batasInput((byte) 100).getKata(TCari));
        TKode.setDocument(new batasInput((byte) 5).getKata(TKode));
        TNama.setDocument(new batasInput((byte) 50).getKata(TNama));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        Scroll = new widget.ScrollPane();
        tbJadwal = new widget.Table();
        jPanel3 = new javax.swing.JPanel();
        panelGlass8 = new widget.panelisi();
        BtnSimpan = new widget.Button();
        BtnBatal = new widget.Button();
        BtnHapus = new widget.Button();
        BtnEdit = new widget.Button();
        BtnImpor = new widget.Button();
        BtnPrint = new widget.Button();
        BtnKeluar = new widget.Button();
        panelGlass9 = new widget.panelisi();
        jLabel6 = new widget.Label();
        TCari = new widget.TextBox();
        BtnCari = new widget.Button();
        BtnAll = new widget.Button();
        jLabel7 = new widget.Label();
        LCount = new widget.Label();
        panelBiasa1 = new widget.PanelBiasa();
        jLabel4 = new widget.Label();
        TKode = new widget.TextBox();
        jLabel12 = new widget.Label();
        TNama = new widget.TextBox();
        jLabel13 = new widget.Label();
        cmbShift = new widget.ComboBox();
        jLabel9 = new widget.Label();
        cmbJam1 = new widget.ComboBox();
        cmbMnt1 = new widget.ComboBox();
        cmbDtk1 = new widget.ComboBox();
        jLabel11 = new widget.Label();
        cmbJam2 = new widget.ComboBox();
        cmbMnt2 = new widget.ComboBox();
        cmbDtk2 = new widget.ComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Jadwal Dinas ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        Scroll.setName("Scroll"); // NOI18N
        Scroll.setOpaque(true);

        tbJadwal.setAutoCreateRowSorter(true);
        tbJadwal.setToolTipText("Silahkan klik untuk memilih data yang mau diedit ataupun dihapus");
        tbJadwal.setName("tbJadwal"); // NOI18N
        tbJadwal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbJadwalMouseClicked(evt);
            }
        });
        tbJadwal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbJadwalKeyPressed(evt);
            }
        });
        Scroll.setViewportView(tbJadwal);

        internalFrame1.add(Scroll, java.awt.BorderLayout.CENTER);

        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(44, 100));
        jPanel3.setLayout(new java.awt.BorderLayout(1, 1));

        panelGlass8.setName("panelGlass8"); // NOI18N
        panelGlass8.setPreferredSize(new java.awt.Dimension(44, 44));
        panelGlass8.setLayout(null);

        BtnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/save-16x16.png"))); // NOI18N
        BtnSimpan.setMnemonic('S');
        BtnSimpan.setText("Simpan");
        BtnSimpan.setToolTipText("Alt+S");
        BtnSimpan.setName("BtnSimpan"); // NOI18N
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });
        BtnSimpan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnSimpanKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnSimpan);
        BtnSimpan.setBounds(6, 10, 95, 30);

        BtnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Cancel-2-16x16.png"))); // NOI18N
        BtnBatal.setMnemonic('B');
        BtnBatal.setText("Baru");
        BtnBatal.setToolTipText("Alt+B");
        BtnBatal.setName("BtnBatal"); // NOI18N
        BtnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatalActionPerformed(evt);
            }
        });
        BtnBatal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnBatalKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnBatal);
        BtnBatal.setBounds(103, 10, 95, 30);

        BtnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/stop_f2.png"))); // NOI18N
        BtnHapus.setMnemonic('H');
        BtnHapus.setText("Hapus");
        BtnHapus.setToolTipText("Alt+H");
        BtnHapus.setName("BtnHapus"); // NOI18N
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });
        BtnHapus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnHapusKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnHapus);
        BtnHapus.setBounds(200, 10, 95, 30);

        BtnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/inventaris.png"))); // NOI18N
        BtnEdit.setMnemonic('G');
        BtnEdit.setText("Ganti");
        BtnEdit.setToolTipText("Alt+G");
        BtnEdit.setName("BtnEdit"); // NOI18N
        BtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditActionPerformed(evt);
            }
        });
        BtnEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnEditKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnEdit);
        BtnEdit.setBounds(297, 10, 95, 30);

        BtnImpor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/file-edit-16x16.png"))); // NOI18N
        BtnImpor.setMnemonic('I');
        BtnImpor.setText("Impor");
        BtnImpor.setToolTipText("Alt+I");
        BtnImpor.setName("BtnImpor"); // NOI18N
        BtnImpor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnImporActionPerformed(evt);
            }
        });
        BtnImpor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnImporKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnImpor);
        BtnImpor.setBounds(394, 10, 95, 30);

        BtnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/b_print.png"))); // NOI18N
        BtnPrint.setMnemonic('T');
        BtnPrint.setText("Cetak");
        BtnPrint.setToolTipText("Alt+T");
        BtnPrint.setName("BtnPrint"); // NOI18N
        BtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrintActionPerformed(evt);
            }
        });
        BtnPrint.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnPrintKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnPrint);
        BtnPrint.setBounds(491, 10, 95, 30);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnKeluar);
        BtnKeluar.setBounds(588, 10, 95, 30);

        jPanel3.add(panelGlass8, java.awt.BorderLayout.CENTER);

        panelGlass9.setName("panelGlass9"); // NOI18N
        panelGlass9.setPreferredSize(new java.awt.Dimension(44, 44));
        panelGlass9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        jLabel6.setText("Key Word :");
        jLabel6.setName("jLabel6"); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(70, 23));
        panelGlass9.add(jLabel6);

        TCari.setName("TCari"); // NOI18N
        TCari.setPreferredSize(new java.awt.Dimension(380, 23));
        TCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TCariKeyPressed(evt);
            }
        });
        panelGlass9.add(TCari);

        BtnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        BtnCari.setMnemonic('3');
        BtnCari.setToolTipText("Alt+3");
        BtnCari.setName("BtnCari"); // NOI18N
        BtnCari.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariActionPerformed(evt);
            }
        });
        BtnCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnCariKeyPressed(evt);
            }
        });
        panelGlass9.add(BtnCari);

        BtnAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Search-16x16.png"))); // NOI18N
        BtnAll.setMnemonic('4');
        BtnAll.setToolTipText("Alt+4");
        BtnAll.setName("BtnAll"); // NOI18N
        BtnAll.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAllActionPerformed(evt);
            }
        });
        BtnAll.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnAllKeyPressed(evt);
            }
        });
        panelGlass9.add(BtnAll);

        jLabel7.setText("Record :");
        jLabel7.setName("jLabel7"); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(65, 23));
        panelGlass9.add(jLabel7);

        LCount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LCount.setText("0");
        LCount.setName("LCount"); // NOI18N
        LCount.setPreferredSize(new java.awt.Dimension(50, 23));
        panelGlass9.add(LCount);

        jPanel3.add(panelGlass9, java.awt.BorderLayout.PAGE_START);

        internalFrame1.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        panelBiasa1.setName("panelBiasa1"); // NOI18N
        panelBiasa1.setPreferredSize(new java.awt.Dimension(1023, 78));
        panelBiasa1.setLayout(null);

        jLabel4.setText("Kode :");
        jLabel4.setName("jLabel4"); // NOI18N
        panelBiasa1.add(jLabel4);
        jLabel4.setBounds(0, 8, 40, 23);

        TKode.setName("TKode"); // NOI18N
        TKode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TKodeKeyPressed(evt);
            }
        });
        panelBiasa1.add(TKode);
        TKode.setBounds(44, 8, 70, 23);

        jLabel12.setText("Nama :");
        jLabel12.setName("jLabel12"); // NOI18N
        panelBiasa1.add(jLabel12);
        jLabel12.setBounds(120, 8, 45, 23);

        TNama.setName("TNama"); // NOI18N
        TNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TNamaKeyPressed(evt);
            }
        });
        panelBiasa1.add(TNama);
        TNama.setBounds(169, 8, 220, 23);

        jLabel13.setText("Mapping ke :");
        jLabel13.setName("jLabel13"); // NOI18N
        panelBiasa1.add(jLabel13);
        jLabel13.setBounds(395, 8, 70, 23);

        cmbShift.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Pagi", "Pagi2", "Pagi3", "Pagi4", "Pagi5", "Pagi6", "Pagi7", "Pagi8", "Pagi9", "Pagi10", "Pagi11", "Pagi12", "Pagi13", "Pagi14", "Pagi15", "Pagi16", "Pagi17", "Pagi18", "Pagi19", "Pagi20", "Pagi21", "Pagi22", "Pagi23", "Pagi24", "Pagi25", "Pagi26", "Pagi27", "Pagi28", "Pagi29", "Pagi30", "Pagi31", "Pagi32", "Pagi33", "Pagi34", "Pagi35", "Pagi36", "Pagi37", "Pagi38", "Pagi39", "Pagi40", "Siang", "Siang2", "Siang3", "Siang4", "Siang5", "Siang6", "Siang7", "Siang8", "Siang9", "Siang10", "Siang11", "Siang12", "Siang13", "Siang14", "Siang15", "Siang16", "Siang17", "Siang18", "Siang19", "Siang20", "Siang21", "Siang22", "Siang23", "Siang24", "Siang25", "Siang26", "Siang27", "Siang28", "Siang29", "Siang30", "Siang31", "Siang32", "Siang33", "Siang34", "Siang35", "Siang36", "Siang37", "Siang38", "Siang39", "Siang40", "Malam", "Malam2", "Malam3", "Malam4", "Malam5", "Malam6", "Malam7", "Malam8", "Malam9", "Malam10", "Malam11", "Malam12", "Malam13", "Malam14", "Malam15", "Malam16", "Malam17", "Malam18", "Malam19", "Malam20", "Malam21", "Malam22", "Malam23", "Malam24", "Malam25", "Malam26", "Malam27", "Malam28", "Malam29", "Malam30", "Malam31", "Malam32", "Malam33", "Malam34", "Malam35", "Malam36", "Malam37", "Malam38", "Malam39", "Malam40", "Midle Pagi1", "Midle Pagi2", "Midle Pagi3", "Midle Pagi4", "Midle Pagi5", "Midle Pagi6", "Midle Pagi7", "Midle Pagi8", "Midle Pagi9", "Midle Pagi10", "Midle Pagi11", "Midle Pagi12", "Midle Pagi13", "Midle Pagi14", "Midle Pagi15", "Midle Pagi16", "Midle Pagi17", "Midle Pagi18", "Midle Pagi19", "Midle Pagi20", "Midle Pagi21", "Midle Pagi22", "Midle Pagi23", "Midle Pagi24", "Midle Pagi25", "Midle Pagi26", "Midle Pagi27", "Midle Pagi28", "Midle Pagi29", "Midle Pagi30", "Midle Pagi31", "Midle Pagi32", "Midle Pagi33", "Midle Pagi34", "Midle Pagi35", "Midle Pagi36", "Midle Pagi37", "Midle Pagi38", "Midle Pagi39", "Midle Pagi40", "Midle Siang1", "Midle Siang2", "Midle Siang3", "Midle Siang4", "Midle Siang5", "Midle Siang6", "Midle Siang7", "Midle Siang8", "Midle Siang9", "Midle Siang10", "Midle Siang11", "Midle Siang12", "Midle Siang13", "Midle Siang14", "Midle Siang15", "Midle Siang16", "Midle Siang17", "Midle Siang18", "Midle Siang19", "Midle Siang20", "Midle Siang21", "Midle Siang22", "Midle Siang23", "Midle Siang24", "Midle Siang25", "Midle Siang26", "Midle Siang27", "Midle Siang28", "Midle Siang29", "Midle Siang30", "Midle Siang31", "Midle Siang32", "Midle Siang33", "Midle Siang34", "Midle Siang35", "Midle Siang36", "Midle Siang37", "Midle Siang38", "Midle Siang39", "Midle Siang40", "Midle Malam1", "Midle Malam2", "Midle Malam3", "Midle Malam4", "Midle Malam5", "Midle Malam6", "Midle Malam7", "Midle Malam8", "Midle Malam9", "Midle Malam10", "Midle Malam11", "Midle Malam12", "Midle Malam13", "Midle Malam14", "Midle Malam15", "Midle Malam16", "Midle Malam17", "Midle Malam18", "Midle Malam19", "Midle Malam20", "Midle Malam21", "Midle Malam22", "Midle Malam23", "Midle Malam24", "Midle Malam25", "Midle Malam26", "Midle Malam27", "Midle Malam28", "Midle Malam29", "Midle Malam30", "Midle Malam31", "Midle Malam32", "Midle Malam33", "Midle Malam34", "Midle Malam35", "Midle Malam36", "Midle Malam37", "Midle Malam38", "Midle Malam39", "Midle Malam40" }));
        cmbShift.setName("cmbShift"); // NOI18N
        cmbShift.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbShiftKeyPressed(evt);
            }
        });
        panelBiasa1.add(cmbShift);
        cmbShift.setBounds(469, 8, 140, 23);

        jLabel9.setText("Jam :");
        jLabel9.setName("jLabel9"); // NOI18N
        panelBiasa1.add(jLabel9);
        jLabel9.setBounds(0, 41, 40, 23);

        cmbJam1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        cmbJam1.setName("cmbJam1"); // NOI18N
        cmbJam1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbJam1KeyPressed(evt);
            }
        });
        panelBiasa1.add(cmbJam1);
        cmbJam1.setBounds(44, 41, 62, 23);

        cmbMnt1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        cmbMnt1.setName("cmbMnt1"); // NOI18N
        cmbMnt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbMnt1KeyPressed(evt);
            }
        });
        panelBiasa1.add(cmbMnt1);
        cmbMnt1.setBounds(109, 41, 62, 23);

        cmbDtk1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        cmbDtk1.setName("cmbDtk1"); // NOI18N
        cmbDtk1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbDtk1KeyPressed(evt);
            }
        });
        panelBiasa1.add(cmbDtk1);
        cmbDtk1.setBounds(174, 41, 62, 23);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("s.d.");
        jLabel11.setName("jLabel11"); // NOI18N
        panelBiasa1.add(jLabel11);
        jLabel11.setBounds(239, 41, 25, 23);

        cmbJam2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        cmbJam2.setName("cmbJam2"); // NOI18N
        cmbJam2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbJam2KeyPressed(evt);
            }
        });
        panelBiasa1.add(cmbJam2);
        cmbJam2.setBounds(267, 41, 62, 23);

        cmbMnt2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        cmbMnt2.setName("cmbMnt2"); // NOI18N
        cmbMnt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbMnt2KeyPressed(evt);
            }
        });
        panelBiasa1.add(cmbMnt2);
        cmbMnt2.setBounds(332, 41, 62, 23);

        cmbDtk2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        cmbDtk2.setName("cmbDtk2"); // NOI18N
        cmbDtk2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbDtk2KeyPressed(evt);
            }
        });
        panelBiasa1.add(cmbDtk2);
        cmbDtk2.setBounds(397, 41, 62, 23);

        internalFrame1.add(panelBiasa1, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TKodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TKodeKeyPressed
        Valid.pindah(evt, BtnAll, TNama);
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            tbJadwal.requestFocus();
        }
    }//GEN-LAST:event_TKodeKeyPressed

    private void TNamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TNamaKeyPressed
        Valid.pindah(evt, TKode, cmbShift);
    }//GEN-LAST:event_TNamaKeyPressed

    private void cmbShiftKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbShiftKeyPressed
        Valid.pindah(evt, TNama, cmbJam1);
    }//GEN-LAST:event_cmbShiftKeyPressed

    private void cmbJam1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbJam1KeyPressed
        Valid.pindah(evt, cmbShift, cmbMnt1);
    }//GEN-LAST:event_cmbJam1KeyPressed

    private void cmbMnt1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbMnt1KeyPressed
        Valid.pindah(evt, cmbJam1, cmbDtk1);
    }//GEN-LAST:event_cmbMnt1KeyPressed

    private void cmbDtk1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbDtk1KeyPressed
        Valid.pindah(evt, cmbMnt1, cmbJam2);
    }//GEN-LAST:event_cmbDtk1KeyPressed

    private void cmbJam2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbJam2KeyPressed
        Valid.pindah(evt, cmbDtk1, cmbMnt2);
    }//GEN-LAST:event_cmbJam2KeyPressed

    private void cmbMnt2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbMnt2KeyPressed
        Valid.pindah(evt, cmbJam2, cmbDtk2);
    }//GEN-LAST:event_cmbMnt2KeyPressed

    private void cmbDtk2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbDtk2KeyPressed
        Valid.pindah(evt, cmbMnt2, BtnSimpan);
    }//GEN-LAST:event_cmbDtk2KeyPressed

    private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanActionPerformed
        if (TKode.getText().trim().isEmpty() || TNama.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Kode dan nama shift harus diisi...!!!!");
            TKode.requestFocus();
            return;
        }

        String kode = TKode.getText().trim().toUpperCase();
        if (Sequel.menyimpantfSmc("jam_masuk_smc", "", kode, TNama.getText().trim(), Valid.getJamSmc(cmbJam1, cmbMnt1, cmbDtk1), Valid.getJamSmc(cmbJam2, cmbMnt2, cmbDtk2))) {
            simpanMappingShift(kode);
            tabMode.addRow(new Object[] {
                false, kode, TNama.getText().trim(), Valid.getJamSmc(cmbJam1, cmbMnt1, cmbDtk1),
                Valid.getJamSmc(cmbJam2, cmbMnt2, cmbDtk2), cmbShift.getSelectedItem().toString()
            });
            emptTeks();
        }
    }//GEN-LAST:event_BtnSimpanActionPerformed

    private void BtnSimpanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnSimpanKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            BtnSimpanActionPerformed(null);
        } else {
            Valid.pindah(evt, cmbDtk2, BtnBatal);
        }
    }//GEN-LAST:event_BtnSimpanKeyPressed

    private void BtnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatalActionPerformed
        emptTeks();
    }//GEN-LAST:event_BtnBatalActionPerformed

    private void BtnBatalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnBatalKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            emptTeks();
        } else {
            Valid.pindah(evt, BtnSimpan, BtnHapus);
        }
    }//GEN-LAST:event_BtnBatalKeyPressed

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
        int gagal = 0;
        for (int i = 0; i < tbJadwal.getRowCount(); i++) {
            if (tbJadwal.getValueAt(i, 0).toString().equals("true")) {
                if (!Sequel.menghapustfSmc("jam_masuk_smc", "kode_shift=?", tbJadwal.getValueAt(i, 1).toString())) {
                    gagal++;
                }
            }
        }
        if (gagal > 0) {
            JOptionPane.showMessageDialog(null, gagal + " shift gagal dihapus, kemungkinan masih dipakai di jadwal pegawai...!!!!");
        }

        tampil();
        emptTeks();
    }//GEN-LAST:event_BtnHapusActionPerformed

    private void BtnHapusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnHapusKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            BtnHapusActionPerformed(null);
        } else {
            Valid.pindah(evt, BtnBatal, BtnEdit);
        }
    }//GEN-LAST:event_BtnHapusKeyPressed

    private void BtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditActionPerformed
        if (kodeLama.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Silahkan pilih dulu data yang mau diganti...!!!!");
            return;
        }
        if (TKode.getText().trim().isEmpty() || TNama.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Kode dan nama shift harus diisi...!!!!");
            TKode.requestFocus();
            return;
        }

        String error = null;
        try {
            Sequel.AutoComitFalse();
            String kode = TKode.getText().trim().toUpperCase();
            if (Sequel.mengupdatetfSmc("jam_masuk_smc", "kode_shift = ?, nama_shift = ?, jam_masuk = ?, jam_pulang = ?", "kode_shift = ?", kode, TNama.getText().trim(), 
                Valid.getJamSmc(cmbJam1, cmbMnt1, cmbDtk1), Valid.getJamSmc(cmbJam2, cmbMnt2, cmbDtk2), tbJadwal.getValueAt(tbJadwal.getSelectedRow(), 1).toString()
            )) {
                if (simpanMappingShift(kode)) {
                    tabMode.setValueAt(kode, tbJadwal.convertRowIndexToModel(tbJadwal.getSelectedRow()), 1);
                    tabMode.setValueAt(TNama.getText().trim(), tbJadwal.convertRowIndexToModel(tbJadwal.getSelectedRow()), 2);
                    tabMode.setValueAt(Valid.getJamSmc(cmbJam1, cmbMnt1, cmbDtk1), tbJadwal.convertRowIndexToModel(tbJadwal.getSelectedRow()), 3);
                    tabMode.setValueAt(Valid.getJamSmc(cmbJam2, cmbMnt2, cmbDtk2), tbJadwal.convertRowIndexToModel(tbJadwal.getSelectedRow()), 4);
                    tabMode.setValueAt(cmbShift.getSelectedItem().toString(), tbJadwal.convertRowIndexToModel(tbJadwal.getSelectedRow()), 5);
                    emptTeks();
                }
            } else {
                error = "Gagal mengganti data, kemungkinan kode shift sudah dipakai...!!!";
            }
        } catch (Exception e) {
            System.out.println("Notif : " + e);
        } finally {
            Sequel.AutoComitTrue();
            if (null != error) {
                JOptionPane.showMessageDialog(null, error, "Peringatan", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_BtnEditActionPerformed

    private void BtnEditKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnEditKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            BtnEditActionPerformed(null);
        } else {
            Valid.pindah(evt, BtnHapus, BtnImpor);
        }
    }//GEN-LAST:event_BtnEditKeyPressed

    private void BtnImporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnImporActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Pilih berkas jadwal dinas");
        chooser.setFileFilter(new FileNameExtensionFilter("Berkas Excel (*.xlsx)", "xlsx"));
        if (chooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) {
            return;
        }

        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        int dilewati = 0;
        Map<String, String[]> impor = new LinkedHashMap<>();
        List<String> bermasalah = new ArrayList<>();
        try (Workbook workbook = WorkbookFactory.create(chooser.getSelectedFile())) {
            Sheet sheet = workbook.getSheetAt(0);
            Set<String> terdaftar = getKodeShift();
            for (int i = 1; i <= sheet.getLastRowNum(); i++) {
                Row baris = sheet.getRow(i);
                if (baris == null) {
                    continue;
                }

                String kode = bacaTeks(baris, KOLOM_KODE).toUpperCase();
                String nama = bacaTeks(baris, KOLOM_NAMA);
                if (kode.isEmpty() && nama.isEmpty()) {
                    dilewati++;
                    continue;
                }
                if (kode.isEmpty() || nama.isEmpty()) {
                    bermasalah.add("Baris " + (i + 1) + " : kode dan nama shift harus terisi keduanya.");
                    continue;
                }
                if (terdaftar.contains(kode)) {
                    bermasalah.add("Baris " + (i + 1) + " : kode " + kode + " sudah terdaftar, ubah lewat tombol Edit.");
                    continue;
                }
                if (impor.containsKey(kode)) {
                    bermasalah.add("Baris " + (i + 1) + " : kode " + kode + " ganda di dalam berkas.");
                    continue;
                }

                impor.put(kode, new String[] {kode, nama, bacaJam(baris, KOLOM_JAM_MASUK), bacaJam(baris, KOLOM_JAM_PULANG)});
            }
        } catch (Exception e) {
            System.out.println("Notifikasi : " + e);
            JOptionPane.showMessageDialog(null, "Gagal membaca berkas, pastikan formatnya sesuai jadwal dinas...!!!!");
            this.setCursor(Cursor.getDefaultCursor());
            return;
        }
        this.setCursor(Cursor.getDefaultCursor());

        if (!bermasalah.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Impor dibatalkan, tidak ada data yang disimpan. Perbaiki " + bermasalah.size() +
                " baris berikut :\n\n" + String.join("\n", bermasalah));
            return;
        }
        if (impor.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tidak ada data yang bisa diimpor, " + dilewati + " baris kosong dilewati...!!!!");
            return;
        }

        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        int diproses = 0;
        String gagal = "";
        for (String[] shift : impor.values()) {
            if (!Sequel.menyimpantfSmc("jam_masuk_smc", "kode_shift, nama_shift, jam_masuk, jam_pulang", shift)) {
                gagal = shift[0];
                break;
            }
            diproses++;
        }
        this.setCursor(Cursor.getDefaultCursor());

        if (!gagal.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Impor berhenti pada kode " + gagal + " karena gagal disimpan. " + diproses +
                " baris sudah tersimpan, " + (impor.size() - diproses) + " baris belum tersimpan...!!!!");
        } else {
            JOptionPane.showMessageDialog(null, "Impor selesai. Diproses " + diproses + " baris, dilewati " + dilewati + " baris.");
        }

        tampil();
        emptTeks();
    }//GEN-LAST:event_BtnImporActionPerformed

    private void BtnImporKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnImporKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            BtnImporActionPerformed(null);
        } else {
            Valid.pindah(evt, BtnEdit, BtnPrint);
        }
    }//GEN-LAST:event_BtnImporKeyPressed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            dispose();
        } else {
            Valid.pindah(evt, BtnPrint, TCari);
        }
    }//GEN-LAST:event_BtnKeluarKeyPressed

    private void BtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrintActionPerformed
        if (ceksukses) {
            JOptionPane.showMessageDialog(null, "Proses loading data belum selesai, silahkan tunggu hingga proses loading selesai...!!!!");
            return;
        }
        if (tabMode.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Maaf, data sudah habis. Tidak ada data yang bisa anda print...!!!!");
            BtnBatal.requestFocus();
        } else if (tabMode.getRowCount() != 0) {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            try {
                try (BufferedWriter bw = new BufferedWriter(new FileWriter(new File("file2.css")))) {
                    bw.write(".isi td{border-right: 1px solid #e2e7dd;font: 8.5px tahoma;height:12px;border-bottom: 1px solid #e2e7dd;background: #ffffff;color:#323232;}.head td{border-right: 1px solid #777777;font: 8.5px tahoma;height:10px;border-bottom: 1px solid #e2e7dd;background: #ffffff;color:#323232;}.isi a{text-decoration:none;color:#8b9b95;padding:0 0 0 0px;font-family: Tahoma;font-size: 8.5px;}.isi2 td{font: 8.5px tahoma;height:12px;background: #ffffff;color:#323232;}.isi3 td{border-right: 1px solid #e2e7dd;font: 8.5px tahoma;height:12px;border-top: 1px solid #e2e7dd;background: #ffffff;color:#323232;}.isi4 td{font: 11px tahoma;height:12px;border-top: 1px solid #e2e7dd;background: #ffffff;color:#323232;}");
                    bw.flush();
                }
                String pilihan = (String) JOptionPane.showInputDialog(null, "Silahkan pilih laporan..!", "Pilihan Cetak", JOptionPane.QUESTION_MESSAGE, null, new Object[] {
                    "Laporan 1 (HTML)", "Laporan 2 (WPS)", "Laporan 3 (CSV)", "Laporan 4 (XLSX)", "Laporan 5 (Jasper)"
                }, "Laporan 4 (XLSX)");
                switch (pilihan) {
                    case "Laporan 1 (HTML)":
                        Valid.exportHtmlSmc("JadwalDinas.html", "Jadwal Dinas", tbJadwal);
                        break;
                    case "Laporan 2 (WPS)":
                        Valid.exportWPSSmc("JadwalDinas.wps", "Jadwal Dinas", tbJadwal);
                        break;
                    case "Laporan 3 (CSV)":
                        Valid.exportCSVSmc("JadwalDinas.csv", tbJadwal);
                        break;
                    case "Laporan 4 (XLSX)":
                        Valid.exportXlsxSmc("JadwalDinas.xlsx", tbJadwal);
                        break;
                    case "Laporan 5 (Jasper)":
                        Map<String, Object> param = new HashMap<>();
                        param.put("namars", akses.getnamars());
                        param.put("alamatrs", akses.getalamatrs());
                        param.put("kotars", akses.getkabupatenrs());
                        param.put("propinsirs", akses.getpropinsirs());
                        param.put("kontakrs", akses.getkontakrs());
                        param.put("emailrs", akses.getemailrs());
                        param.put("logo", Sequel.cariGambar("select setting.logo from setting"));
                        Valid.MyReportqry("rptJammasuk.jasper", "report", "::[ Jadwal Dinas ]::",
                            "select * from jam_masuk_smc where kode_shift like '%" + TCari.getText().trim() + "%' or nama_shift like '%" + TCari.getText().trim() + "%' order by kode_shift", param);
                        break;
                }
            } catch (Exception e) {
                System.out.println("Notifikasi : " + e);
            }
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnPrintActionPerformed

    private void BtnPrintKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnPrintKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            BtnPrintActionPerformed(null);
        } else {
            Valid.pindah(evt, BtnImpor, BtnKeluar);
        }
    }//GEN-LAST:event_BtnPrintKeyPressed

    private void TCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCariKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            BtnCariActionPerformed(null);
        } else if (evt.getKeyCode() == KeyEvent.VK_PAGE_DOWN) {
            BtnCari.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_PAGE_UP) {
            BtnKeluar.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            tbJadwal.requestFocus();
        }
    }//GEN-LAST:event_TCariKeyPressed

    private void BtnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariActionPerformed
        tampil();
    }//GEN-LAST:event_BtnCariActionPerformed

    private void BtnCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnCariKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            BtnCariActionPerformed(null);
        } else {
            Valid.pindah(evt, TCari, BtnAll);
        }
    }//GEN-LAST:event_BtnCariKeyPressed

    private void BtnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAllActionPerformed
        tampil();
        TCari.setText("");
    }//GEN-LAST:event_BtnAllActionPerformed

    private void BtnAllKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnAllKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            tampil();
            TCari.setText("");
        } else {
            Valid.pindah(evt, BtnCari, TKode);
        }
    }//GEN-LAST:event_BtnAllKeyPressed

    private void tbJadwalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbJadwalMouseClicked
        if (tabMode.getRowCount() != 0) {
            try {
                getData();
            } catch (java.lang.NullPointerException e) {
            }
        }
    }//GEN-LAST:event_tbJadwalMouseClicked

    private void tbJadwalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbJadwalKeyPressed
        if (tabMode.getRowCount() != 0) {
            if ((evt.getKeyCode() == KeyEvent.VK_ENTER) || (evt.getKeyCode() == KeyEvent.VK_UP) || (evt.getKeyCode() == KeyEvent.VK_DOWN)) {
                try {
                    getData();
                } catch (java.lang.NullPointerException e) {
                }
            }
        }
    }//GEN-LAST:event_tbJadwalKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        tampil();
        if (koneksiDB.CARICEPAT().equals("aktif")) {
            TCari.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
                @Override
                public void insertUpdate(DocumentEvent e) {
                    if (TCari.getText().length() > 2) {
                        tampil();
                    }
                }

                @Override
                public void removeUpdate(DocumentEvent e) {
                    if (TCari.getText().length() > 2) {
                        tampil();
                    }
                }

                @Override
                public void changedUpdate(DocumentEvent e) {
                    if (TCari.getText().length() > 2) {
                        tampil();
                    }
                }
            });
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgJamMasukSMC dialog = new DlgJamMasukSMC(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnAll;
    private widget.Button BtnBatal;
    private widget.Button BtnCari;
    private widget.Button BtnEdit;
    private widget.Button BtnHapus;
    private widget.Button BtnImpor;
    private widget.Button BtnKeluar;
    private widget.Button BtnPrint;
    private widget.Button BtnSimpan;
    private widget.Label LCount;
    private widget.ScrollPane Scroll;
    private widget.TextBox TCari;
    private widget.TextBox TKode;
    private widget.TextBox TNama;
    private widget.ComboBox cmbDtk1;
    private widget.ComboBox cmbDtk2;
    private widget.ComboBox cmbJam1;
    private widget.ComboBox cmbJam2;
    private widget.ComboBox cmbMnt1;
    private widget.ComboBox cmbMnt2;
    private widget.ComboBox cmbShift;
    private widget.InternalFrame internalFrame1;
    private widget.Label jLabel11;
    private widget.Label jLabel12;
    private widget.Label jLabel13;
    private widget.Label jLabel4;
    private widget.Label jLabel6;
    private widget.Label jLabel7;
    private widget.Label jLabel9;
    private javax.swing.JPanel jPanel3;
    private widget.PanelBiasa panelBiasa1;
    private widget.panelisi panelGlass8;
    private widget.panelisi panelGlass9;
    private widget.Table tbJadwal;
    // End of variables declaration//GEN-END:variables

    private void tampil() {
        if (!ceksukses) {
            ceksukses = true;
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            Valid.tabelKosongSmc(tabMode);
            LCount.setText("0");
            new SwingWorker<Void, Object[]>() {
                final String cari = TCari.getText().trim();

                @Override
                protected Void doInBackground() throws Exception {
                    try (PreparedStatement ps = koneksi.prepareStatement(
                        "select jam_masuk_smc.kode_shift, jam_masuk_smc.nama_shift, jam_masuk_smc.jam_masuk, jam_masuk_smc.jam_pulang, ifnull(set_kode_shift_smc.shift, '') as shift " +
                        "from jam_masuk_smc left join set_kode_shift_smc on jam_masuk_smc.kode_shift = set_kode_shift_smc.kode_shift " + (cari.isBlank() ? "" : "where (" +
                        "jam_masuk_smc.kode_shift like ? or jam_masuk_smc.nama_shift like ?) ") + "order by jam_masuk_smc.kode_shift"
                    )) {
                        int p = 0;
                        if (!cari.isBlank()) {
                            ps.setString(++p, "%" + cari + "%");
                            ps.setString(++p, "%" + cari + "%");
                        }
                        try (ResultSet rs = ps.executeQuery()) {
                            while (rs.next()) {
                                publish(new Object[] {
                                    false, rs.getString("kode_shift"), rs.getString("nama_shift"), rs.getString("jam_masuk"), rs.getString("jam_pulang"), rs.getString("shift")
                                });
                            }
                        }
                    }
                    return null;
                }

                @Override
                protected void process(List<Object[]> chunks) {
                    chunks.forEach(tabMode::addRow);
                }

                @Override
                protected void done() {
                    try {
                        get();
                    } catch (Exception e) {
                        System.out.println("Notif : " + e);
                    }
                    tabMode.fireTableDataChanged();
                    LCount.setText(tabMode.getRowCount() + "");
                    DlgJamMasukSMC.this.setCursor(Cursor.getDefaultCursor());
                    ceksukses = false;
                }
            }.execute();
        }
    }

    public void emptTeks() {
        kodeLama = "";
        TKode.setText("");
        TNama.setText("");
        cmbShift.setSelectedItem(TANPA_SHIFT);
        cmbJam1.setSelectedItem("00");
        cmbJam2.setSelectedItem("00");
        cmbMnt1.setSelectedItem("00");
        cmbMnt2.setSelectedItem("00");
        cmbDtk1.setSelectedItem("00");
        cmbDtk2.setSelectedItem("00");

        TKode.requestFocus();
    }

    private void getData() {
        int row = tbJadwal.getSelectedRow();
        if (row != -1) {
            kodeLama = tbJadwal.getValueAt(row, 1).toString();
            TKode.setText(kodeLama);
            TNama.setText(tbJadwal.getValueAt(row, 2).toString());
            cmbJam1.setSelectedItem(tbJadwal.getValueAt(row, 3).toString().substring(0, 2));
            cmbMnt1.setSelectedItem(tbJadwal.getValueAt(row, 3).toString().substring(3, 5));
            cmbDtk1.setSelectedItem(tbJadwal.getValueAt(row, 3).toString().substring(6, 8));
            cmbJam2.setSelectedItem(tbJadwal.getValueAt(row, 4).toString().substring(0, 2));
            cmbMnt2.setSelectedItem(tbJadwal.getValueAt(row, 4).toString().substring(3, 5));
            cmbDtk2.setSelectedItem(tbJadwal.getValueAt(row, 4).toString().substring(6, 8));
            if (tbJadwal.getValueAt(row, 5).toString().isEmpty()) {
                cmbShift.setSelectedItem(TANPA_SHIFT);
            } else {
                cmbShift.setSelectedItem(tbJadwal.getValueAt(row, 5).toString());
            }
        }
    }

    private boolean simpanMappingShift(String kode) {
        String shift = cmbShift.getSelectedItem().toString();
        if (TANPA_SHIFT.equals(shift)) {
            return Sequel.menghapustfSmc("set_kode_shift_smc", "kode_shift = ?", kode);
        }

        return Sequel.menghapustfSmc("set_kode_shift_smc", "shift = ? and kode_shift != ?", shift, kode) &&
            Sequel.executeRawSmc("insert into set_kode_shift_smc (shift, kode_shift) values (?, ?) on duplicate key update shift = values(shift)", shift, kode);
    }

    private Set<String> getKodeShift() {
        Set<String> kode = new LinkedHashSet<>();
        try (PreparedStatement ps = koneksi.prepareStatement("select kode_shift from jam_masuk_smc")) {
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    kode.add(rs.getString("kode_shift"));
                }
            }
        } catch (Exception e) {
            System.out.println("Notif : " + e);
        }
        return kode;
    }

    private String bacaTeks(Row baris, int kolom) {
        Cell cell = baris.getCell(kolom);
        if (cell == null) {
            return "";
        }
        if (CellType.NUMERIC.equals(cell.getCellType())) {
            return String.valueOf((long) cell.getNumericCellValue());
        }
        return cell.getStringCellValue().trim();
    }

    private String bacaJam(Row baris, int kolom) {
        Cell cell = baris.getCell(kolom);
        if (cell == null || !CellType.NUMERIC.equals(cell.getCellType())) {
            return "00:00:00";
        }

        int menit = (int) Math.round(cell.getNumericCellValue() * 1440d) % 1440;
        if (menit < 0) {
            menit = menit + 1440;
        }
        return String.format("%02d:%02d:00", menit / 60, menit % 60);
    }

    public void isCek() {
        BtnSimpan.setEnabled(akses.getjam_masuk_smc());
        BtnHapus.setEnabled(akses.getjam_masuk_smc());
        BtnEdit.setEnabled(akses.getjam_masuk_smc());
        BtnImpor.setEnabled(akses.getjam_masuk_smc());
    }

    public JTable getTable() {
        return tbJadwal;
    }
}
